const DB_COLLOCATIONS = {
collocations: [
  { type:'mc', q:'The prime minister carried ___ a radical reshuffle of the cabinet.', options:['out','over','on','through'], a:'out' },
  { type:'mc', q:'The scandal ___ serious questions about the regulator\'s independence.', options:['raises','makes','brings','does'], a:'raises' },
  { type:'mc', q:'The board reached a ___ decision after several months of deliberation.', options:['unanimous','united','shared','joint'], a:'unanimous' },
  { type:'mc', q:'The ruling ___ serious doubt on the legality of the convictions.', options:['casts','throws','puts','places'], a:'casts' },
  { type:'mc', q:'The senator ___ the blame for the failure squarely on the regulator.', options:['laid','put','placed','threw'], a:'laid' },
  { type:'mc', q:'The new policy will ___ a significant burden on small businesses.', options:['impose','place','put','lay'], a:'impose' },
  { type:'mc', q:'His speech ___ a powerful impression on the delegates.', options:['left','made','gave','had'], a:'left' },
  { type:'mc', q:'She ___ a compelling case for reforming the system.', options:['made','argued','gave','presented'], a:'made' },
  { type:'mc', q:'The evidence was ___ conclusive — there was no room for doubt.', options:['utterly','deeply','completely','absolutely'], a:'utterly' },
  { type:'mc', q:'Years of investment are finally beginning to ___ fruit.', options:['bear','give','produce','yield'], a:'bear' },
  { type:'mc', q:'The agreement ___ the way for full diplomatic relations.', options:['paves','opens','clears','makes'], a:'paves' },
  { type:'mc', q:'The ruling ___ a dangerous precedent for future cases.', options:['sets','makes','creates','forms'], a:'sets' },
  { type:'mc', q:'Each scandal ___ public confidence further.', options:['eroded','reduced','diminished','weakened'], a:'eroded' },
  { type:'mc', q:'Her analytical skills ___ her out as an exceptional candidate.', options:['mark','set','point','single'], a:'mark' },
  { type:'mc', q:'The policy aims to ___ the gap between rich and poor.', options:['bridge','close','fill','narrow'], a:'bridge' },
  { type:'mc', q:'The results ___ conventional economic logic.', options:['defy','challenge','break','contradict'], a:'defy' },
  { type:'mc', q:'The lobbyists ___ considerable pressure on legislators.', options:['exerted','applied','put','placed'], a:'exerted' },
  { type:'mc', q:'We must ___ a clear distinction between correlation and causation.', options:['draw','make','establish','create'], a:'draw' },
  { type:'mc', q:'She ___ a robust defence of her actions before the committee.', options:['mounted','made','provided','offered'], a:'mounted' },
  { type:'mc', q:'The findings ___ counter to prevailing assumptions.', options:['run','go','work','stand'], a:'run' },
  { type:'mc', q:'The problems ___ from decades of underinvestment.', options:['stem','come','originate','result'], a:'stem' },
  { type:'mc', q:'Ideology continues to ___ sway over economic policy.', options:['hold','have','exert','keep'], a:'hold' },
  { type:'mc', q:'The panel was unable to ___ a consensus on the cause of the failure.', options:['reach','achieve','arrive at','all of the above'], a:'all of the above' },
  { type:'mc', q:'Years of sustained pressure have ___ a heavy toll on the team.', options:['taken','had','left','made'], a:'taken' },
  { type:'mc', q:'The scandal ___ at the heart of the institution\'s credibility.', options:['strikes','hits','gets','cuts'], a:'strikes' },
  { type:'mc', q:'The vote represented a ___ shift in the political landscape.', options:['seismic','radical','dramatic','fundamental'], a:'seismic' },
  { type:'mc', q:'The media coverage risks ___ harmful stereotypes.', options:['perpetuating','reinforcing','both a and b','spreading'], a:'both a and b' },
  { type:'mc', q:'The new evidence ___ the prosecution\'s theory.', options:['corroborates','supports','both a and b','validates'], a:'both a and b' },
  { type:'mc', q:'She ___ the situation with admirable composure and decisiveness.', options:['handled','managed','both a and b','dealt with'], a:'both a and b' },
  { type:'mc', q:'The findings ___ considerable weight to the original hypothesis.', options:['give','lend','add','both a and b'], a:'both a and b' },
  { type:'fill', q:'The documentary shed ___ on a largely forgotten period of history.', a:'light' },
  { type:'fill', q:'His remarks were taken out of ___.', a:'context' },
  { type:'fill', q:'She struck a ___ between firmness and compassion in her leadership.', a:'balance' },
  { type:'fill', q:'The government is under enormous ___ to reduce the deficit.', a:'pressure' },
  { type:'fill', q:'The decision has far-reaching ___ for the entire sector.', a:'implications' },
  { type:'fill', q:'The two leaders reached an ___ on all the key points.', a:'agreement' },
  { type:'fill', q:'She gave a ___ account of what had transpired during the meeting.', a:'detailed' },
  { type:'fill', q:'The two companies are in direct ___ for the same government contract.', a:'competition' },
  { type:'fill', q:'The new policy has come under intense ___ from opposition groups.', a:'scrutiny' },
  { type:'fill', q:'The proposals sparked a fierce ___ in parliament.', a:'debate' },
  { type:'fill', q:'Frontline workers bore the ___ of the criticism from the inquiry.', a:'brunt' },
  { type:'fill', q:'There is a glaring ___ in his account that nobody has addressed.', a:'inconsistency' },
  { type:'fill', q:'The figures are a stark ___ of the scale of the problem.', a:'reminder' },
  { type:'fill', q:'The opposition is gradually ___ ground in the polls.', a:'gaining' },
  { type:'fill', q:'She gave ___ to the campaign by publicly endorsing the policy.', a:'weight', hint:'"Give weight to" = lend credibility or importance.' },
  { type:'fill', q:'The committee was charged with ___ the root cause of the failure.', a:'establishing', hint:'"Establish the root cause" = determine the fundamental source.' },
  { type:'fill', q:'The government has ___ sweeping powers to detain suspects.', a:'granted', hint:'"Grant powers" = formally give authority.' },
  { type:'fill', q:'The evidence ___ a need for immediate regulatory intervention.', a:'points to', hint:'"Point to" = indicate; suggest.' },
  { type:'fill', q:'The two reports are fundamentally ___ odds with each other.', a:'at', hint:'"At odds with" = in conflict or disagreement.' },
  { type:'fill', q:'The proposal was rejected on the ___ that it was financially unviable.', a:'grounds', hint:'"On the grounds that" = using this as the reason.' },
  { type:'fill', q:'The initiative has ___ considerable momentum over the past year.', a:'gathered', hint:'"Gather momentum" = increase in speed or support.' },
  { type:'fill', q:'The scandal has ___ irreparable damage to the institution\'s reputation.', a:'caused', hint:'"Cause irreparable damage" = produce damage that cannot be repaired.' },
  { type:'fill', q:'The new policy ___ a significant departure from previous practice.', a:'represents', hint:'"Represent a departure" = constitute a change from the norm.' },
  { type:'fill', q:'The hearing was ___ to assess whether sufficient grounds existed.', a:'convened', hint:'"Convene a hearing" = formally bring together for a hearing.' },
  { type:'fill', q:'She ___ a precedent by refusing to testify, which others later followed.', a:'set', hint:'"Set a precedent" = establish a standard for future cases.' },
],

};
