const DB_CONFUSABLES = {
confusables: [
  { type:'mc', q:'"The company\'s financial ___ is worse than last year." AFFECT or EFFECT?', options:['effect','affect'], a:'effect' },
  { type:'mc', q:'"The scandal will ___ the company\'s reputation." AFFECT or EFFECT?', options:['affect','effect'], a:'affect' },
  { type:'mc', q:'"There were ___ participants than expected." FEWER or LESS?', options:['fewer','less'], a:'fewer' },
  { type:'mc', q:'"___ the report was incomplete, it contained valuable insights." ALTHOUGH or DESPITE?', options:['Although','Despite'], a:'Although' },
  { type:'mc', q:'"The board ___ to approve the merger unanimously." AGREED or ACCEPTED?', options:['agreed','accepted'], a:'agreed' },
  { type:'mc', q:'"She ___ a very influential role in the negotiations." PLAYED or MADE?', options:['played','made'], a:'played' },
  { type:'mc', q:'"The policy will ___ in significant changes." RESULT or CAUSE?', options:['result','cause'], a:'result' },
  { type:'mc', q:'"The findings ___ a need for reform." IMPLY or INFER?', options:['imply','infer'], a:'imply' },
  { type:'mc', q:'"The minister ___ responsibility for the failure." ACCEPTED or ADMITTED?', options:['accepted','admitted'], a:'accepted' },
  { type:'mc', q:'"The company\'s losses were ___." ECONOMIC or ECONOMICAL?', options:['economic','economical'], a:'economic' },
  { type:'mc', q:'"She gave a very ___ account of the meeting." COMPREHENSIVE or COMPREHENSIBLE?', options:['comprehensive','comprehensible'], a:'comprehensive' },
  { type:'mc', q:'"The decision had ___ consequences." FARTHER or FURTHER?', options:['further','farther'], a:'further' },
  { type:'mc', q:'"He was ___ by the complexity of the problem." DAUNTED or DAUNTING?', options:['daunted','daunting'], a:'daunted' },
  { type:'mc', q:'We need a ___ party to arbitrate — no personal stake. DISINTERESTED or UNINTERESTED?', options:['disinterested','uninterested'], a:'disinterested' },
  { type:'mc', q:'"The committee ___ seven members." COMPRISES or IS COMPRISED OF?', options:['comprises','is comprised of'], a:'comprises' },
  { type:'mc', q:'"The law ___ the use of chemical weapons." PRESCRIBES or PROSCRIBES?', options:['proscribes','prescribes'], a:'proscribes' },
  { type:'mc', q:'"She ___ the allegations with documentary evidence." REFUTED or DENIED?', options:['refuted','denied'], a:'refuted' },
  { type:'mc', q:'"The meeting takes place on ___ Tuesdays — every other week." ALTERNATE or ALTERNATIVE?', options:['alternate','alternative'], a:'alternate' },
  { type:'mc', q:'Continuous vs Continual: "The machine runs ___ — never stops."', options:['continuously','continually'], a:'continuously' },
  { type:'mc', q:'"This is a ___ moment — it will change everything that follows." HISTORIC or HISTORICAL?', options:['historic','historical'], a:'historic' },
  { type:'mc', q:'"No ___ alternative was identified by the committee." PRACTICABLE or PRACTICAL?', options:['practicable','practical'], a:'practicable' },
  { type:'mc', q:'"The ___ of the crime slowly became apparent." ENORMITY or ENORMOUSNESS?', options:['enormity','enormousness'], a:'enormity' },
  { type:'mc', q:'"She ___ the point, albeit reluctantly." CONCEDED or ADMITTED?', options:['conceded','admitted'], a:'conceded' },
  { type:'mc', q:'Steps were taken to ___ the environmental impact. MITIGATE or MILITATE?', options:['mitigate','militate'], a:'mitigate' },
  { type:'mc', q:'Please keep me ___ of any developments. APPRISED or APPRAISED?', options:['apprised','appraised'], a:'apprised' },
  { type:'mc', q:'"He was characteristically ___ about his personal life." RETICENT or RELUCTANT?', options:['reticent','reluctant'], a:'reticent' },
  { type:'mc', q:'"The ___ effects of the drug were well-documented." ADVERSE or AVERSE?', options:['adverse','averse'], a:'adverse', hint:'"Adverse" = harmful/negative (things). "Averse" = opposed (people, usually "averse to").' },
  { type:'mc', q:'"She was ___ to taking risks and preferred caution." ADVERSE or AVERSE?', options:['averse','adverse'], a:'averse', hint:'"Averse to" = opposed/reluctant (used of people). "Adverse" = harmful (used of conditions).' },
  { type:'mc', q:'"The speech was ___ — boring and long." INTERMINABLE or INTERMINABLE?', options:['interminable','insufferable','both mean very long/tedious','neither'], a:'interminable', hint:'"Interminable" = seemingly endless. "Insufferable" = unbearable, usually of people.' },
  { type:'mc', q:'"She showed great ___ in her handling of the sensitive issue." DISCRETION or DISCREETNESS?', options:['discretion','discreetness'], a:'discretion', hint:'"Discretion" = careful judgement; also "at one\'s discretion". "Discreetness" is rare and redundant.' },
  { type:'mc', q:'"He was ___ about the outcome, predicting both success and failure." AMBIGUOUS or AMBIVALENT?', options:['ambivalent','ambiguous'], a:'ambivalent', hint:'"Ambivalent" = having mixed feelings (people). "Ambiguous" = unclear in meaning (language/situations).' },
  { type:'mc', q:'"The wording of the clause is ___." AMBIGUOUS or AMBIVALENT?', options:['ambiguous','ambivalent'], a:'ambiguous', hint:'"Ambiguous" = open to more than one interpretation (language). "Ambivalent" = mixed feelings (people).' },
]

};
