const DB_ERROR = {
error: [
  { type:'error', sentence:'Despite of the evidence, the board refused to act.', correction:'Despite the evidence', explanation:'"Despite" is never followed by "of". "In spite of" uses "of", but "despite" does not.' },
  { type:'error', sentence:'She suggested to reconsider the proposal before the deadline.', correction:'suggested reconsidering', explanation:'"Suggest" takes a gerund (-ing), not an infinitive.' },
  { type:'error', sentence:'The data shows that unemployment is raising.', correction:'is rising', explanation:'"Rise" is intransitive (no object). "Raise" requires an object.' },
  { type:'error', sentence:'I look forward to hear from you at your earliest convenience.', correction:'to hearing', explanation:'"Look forward to" is followed by a gerund, not an infinitive.' },
  { type:'error', sentence:'The report consists of three mains sections.', correction:'main sections', explanation:'"Main" is an adjective and does not take a plural -s.' },
  { type:'error', sentence:'She made me to reconsider the entire strategy.', correction:'made me reconsider', explanation:'Causative "make" takes a bare infinitive — no "to".' },
  { type:'error', sentence:'Hardly he had arrived when the meeting began.', correction:'Hardly had he arrived', explanation:'Inversion is required after "Hardly" at the start of a sentence.' },
  { type:'error', sentence:'The policy has far-reaching effects in unemployment.', correction:'on unemployment', explanation:'"Effects on" something — not "in".' },
  { type:'error', sentence:'She is used to work under pressure.', correction:'used to working', explanation:'"Be used to" is followed by a gerund.' },
  { type:'error', sentence:'The proposal was both illogical as well as poorly costed.', correction:'both illogical and poorly costed', explanation:'"Both...and..." is the correct correlative conjunction.' },
  { type:'error', sentence:'I would have preferred if they informed me in advance.', correction:'had informed me', explanation:'After "would have preferred", use a past perfect in the subordinate clause.' },
  { type:'error', sentence:'The research sheds a light on previously overlooked factors.', correction:'sheds light on', explanation:'"Shed light on" has no article — it\'s a fixed expression.' },
  { type:'error', sentence:'He was accused for misappropriating public funds.', correction:'accused of', explanation:'"Accused of" — not "for".' },
  { type:'error', sentence:'Not only she lied, but she also destroyed the evidence.', correction:'Not only did she lie', explanation:'Inversion is required after "Not only" at the start of a clause.' },
  { type:'error', sentence:'The chairman made a speech consisting in three parts.', correction:'consisting of', explanation:'"Consist of" — not "in".' },
  { type:'error', sentence:'They were able to rise enough capital for the venture.', correction:'raise enough capital', explanation:'"Raise capital" is the correct collocation. "Rise" is intransitive.' },
  { type:'error', sentence:'No sooner had she arrived when the problems started.', correction:'than the problems started', explanation:'"No sooner...than" — always "than", never "when".' },
  { type:'error', sentence:'The government is comprised of twelve ministers.', correction:'comprises twelve ministers', explanation:'"Comprise" takes no "of". "The whole comprises the parts". "Comprised of" is formally incorrect.' },
  { type:'error', sentence:'Seldom she had seen such a blatant misuse of power.', correction:'Seldom had she seen', explanation:'Inversion is required after "Seldom" at the start of a sentence.' },
  { type:'error', sentence:'The number of applicants are higher than expected.', correction:'is higher', explanation:'"The number of" takes a singular verb. Contrast: "A number of applicants are...".' },
  { type:'error', sentence:'She denied to have taken the documents.', correction:'denied having taken', explanation:'"Deny" is followed by a gerund, not an infinitive.' },
  { type:'error', sentence:'He insisted that she should leave immediately.', correction:'insisted that she leave', explanation:'After "insist that" in formal usage, the subjunctive is used (base form).' },
  { type:'error', sentence:'Neither the CEO nor the board were informed in advance.', correction:'was informed', explanation:'"Neither...nor..." takes a singular verb when both subjects are singular.' },
  { type:'error', sentence:'She is more experienced than any member of the team.', correction:'any other member', explanation:'"Any other member" is correct when comparing within a group; "any member" implies she is not a member.' },
  { type:'error', sentence:'The minister refuted the allegations, saying they were false.', correction:'denied / rejected', explanation:'"Refute" means to disprove conclusively. Simply saying allegations are false is "denying" or "rejecting" them.' },
  { type:'error', sentence:'He would have preferred that she would attend in person.', correction:'that she attend / had attended', explanation:'After "would have preferred that", use the subjunctive or past perfect.' },
  { type:'error', sentence:'The report, which it was published last year, has been widely cited.', correction:'which was published', explanation:'"Which" already acts as the subject — no pronoun "it" needed.' },
  { type:'error', sentence:'The committee was laid with the responsibility of oversight.', correction:'charged with / tasked with', explanation:'"Laid with" is not standard. Use "charged with" or "tasked with".' },
  { type:'error', sentence:'The decision is opened to interpretation.', correction:'open to interpretation', explanation:'"Open to interpretation" — adjective "open", not past participle "opened".' },
  { type:'error', sentence:'It\'s high time the government takes action on this issue.', correction:'took action', explanation:'"It\'s high time + past subjunctive". The verb after "it\'s high time" must be in the past tense.' },
  { type:'error', sentence:'The evidence is mounting up that the policy has failed.', correction:'is mounting', explanation:'"Mount" is used without "up" in this figurative sense. "Evidence mounts" or "is mounting" — not "mounting up".' },
  { type:'error', sentence:'Despite having studied for months, yet she failed the exam.', correction:'she failed the exam', explanation:'"Despite" already introduces the concession — "yet" is redundant and incorrect here.' },
],

};
