const DB_FIXED = {
fixed: [
  { type:'mc', q:'___ the evidence available, it would be premature to draw firm conclusions.', options:['Given','Because of','Due to','Since'], a:'Given' },
  { type:'mc', q:'The project ran over budget. ___, the outcomes exceeded all expectations.', options:['That said','Moreover','To that end','In addition'], a:'That said' },
  { type:'mc', q:'The allegations, ___ proven, could irreparably damage the firm\'s reputation.', options:['if substantiated','in case proven','when confirmed','once proved'], a:'if substantiated' },
  { type:'mc', q:'The decision was taken ___ the advice of the legal team.', options:['against','despite','contrary to','in spite of'], a:'against' },
  { type:'mc', q:'The committee was ___ no illusions about the scale of the challenge.', options:['under','with','in','at'], a:'under' },
  { type:'mc', q:'___ from a few minor inconsistencies, the report is thorough.', options:['Apart','Aside','Other','Except'], a:'Apart' },
  { type:'mc', q:'He spoke ___ to the point — no preamble, no hedging.', options:['straight','directly','bluntly','frankly'], a:'straight' },
  { type:'mc', q:'She passed the exam with ___ colours.', options:['flying','bright','glowing','shining'], a:'flying' },
  { type:'mc', q:'Her analysis was ___ the mark — it failed to address the core issue.', options:['wide of','far from','short of','out of'], a:'wide of' },
  { type:'mc', q:'___ it to say, the outcome was not what anyone had hoped for.', options:['Suffice','Leave','Allow','Let'], a:'Suffice' },
  { type:'mc', q:'She told him ___ no uncertain terms that his conduct was unacceptable.', options:['in','with','by','at'], a:'in' },
  { type:'mc', q:'We need more staff. ___ that end, the training budget has been doubled.', options:['To','For','With','In'], a:'To' },
  { type:'mc', q:'This is ___ no means a simple matter.', options:['by','in','at','on'], a:'by' },
  { type:'mc', q:'___ retrospect, the early warning signs were clearly visible.', options:['In','With','On','By'], a:'In' },
  { type:'mc', q:'The committee will publish its findings in due ___.', options:['course','time','order','process'], a:'course' },
  { type:'mc', q:'The matter has, ___ all intents and purposes, been resolved.', options:['for','by','in','to'], a:'for' },
  { type:'mc', q:'"___ the benefit of hindsight, the decision was clearly an error."', options:['With','In','By','From'], a:'With' },
  { type:'mc', q:'The policy represents a paradigm ___ in how the state approaches welfare.', options:['shift','change','break','turn'], a:'shift' },
  { type:'mc', q:'"Taking everything ___ account, the proposal represents a reasonable compromise."', options:['into','in','on','at'], a:'into' },
  { type:'mc', q:'"These figures should not be taken at ___ value without deeper analysis."', options:['face','full','plain','surface'], a:'face' },
  { type:'mc', q:'"The two departments have been working at cross ___."', options:['purposes','wires','aims','lines'], a:'purposes' },
  { type:'mc', q:'"Whether the original decision was correct is now a ___ point."', options:['moot','grey','fine','debatable'], a:'moot' },
  { type:'mc', q:'"The letter was sent ___ prejudice and cannot be used as evidence."', options:['without','against','in','under'], a:'without' },
  { type:'mc', q:'"In the ___ vein, the second report also concludes that intervention is needed."', options:['same','similar','related','identical'], a:'same' },
  { type:'mc', q:'"The new testimony ___ credence to the prosecution\'s case."', options:['lends','gives','adds','brings'], a:'lends' },
  { type:'fill', q:'Notwithstanding the above, it is ___ noting that several exceptions apply.', a:'worth' },
  { type:'fill', q:'The decision was made in ___ of the expert committee\'s recommendation.', a:'defiance' },
  { type:'fill', q:'The company, for all intents and ___, has ceased to operate.', a:'purposes' },
  { type:'fill', q:'The findings are open to ___ — different researchers may interpret them differently.', a:'interpretation' },
  { type:'fill', q:'There is no ___ for such gross negligence.', a:'excuse' },
  { type:'fill', q:'The minister was accused of giving a watered-down ___ of the truth.', a:'version' },
  { type:'fill', q:'The fact of the ___ is that no easy solution exists.', a:'matter' },
  { type:'fill', q:'All things being ___, the project should be completed on schedule.', a:'equal' },
  { type:'fill', q:'In the long ___, investment in education yields the greatest returns.', a:'run' },
  { type:'fill', q:'She told him, ___ no uncertain terms, that his conduct was unacceptable.', a:'in' },
  { type:'fill', q:'The decision was justified, ___ as no other option was available.', a:'inasmuch' },
  { type:'fill', q:'He succeeded against all ___, despite being the clear underdog.', a:'odds' },
  { type:'fill', q:'The findings were published ___ the auspices of the Royal Society.', a:'under' },
  { type:'fill', q:'The contract was awarded by a ___ margin over the rival bid.', a:'narrow', hint:'"By a narrow margin" = by a small amount.' },
  { type:'fill', q:'The proposal was defeated by a ___ margin.', a:'wide', hint:'"By a wide margin" = by a large amount; decisively.' },
  { type:'fill', q:'___ the record, I was not present at that meeting.', a:'For', hint:'"For the record" = to state officially.' },
  { type:'fill', q:'His behaviour was, to say the ___,  highly inappropriate.', a:'least', hint:'"To say the least" = understating something strongly.' },
  { type:'fill', q:'The case rests ___ the assumption that all parties acted in good faith.', a:'on', hint:'"Rest on" = depend on; be based on.' },
],

};
