const DB_IDIOMS = {
idioms: [
  // Already tested idioms — kept brief
  { type:'mc', q:'"The minister has been sitting on the fence." She is:', options:['avoiding commitment','actively debating','opposing the view','in favour'], a:'avoiding commitment' },
  { type:'mc', q:'"The union finally had the upper hand." This means:', options:['an advantage','more members','a better lawyer','more time'], a:'an advantage' },
  { type:'mc', q:'"The company would weather the storm." It would:', options:['survive the crisis','change strategy','seek help','restructure'], a:'survive the crisis' },
  { type:'mc', q:'"She burned her bridges." She:', options:['damaged future relationships','resigned','was dismissed','was promoted'], a:'damaged future relationships' },
  { type:'mc', q:'"Let\'s not reinvent the wheel." We should:', options:['use what already works','be more creative','start fresh','innovate more'], a:'use what already works' },
  { type:'mc', q:'"The treasurer said finances were in the red." This means:', options:['losing money','profitable','under audit','stable'], a:'losing money' },
  { type:'mc', q:'"He pulled strings." He:', options:['used influence','worked hard','negotiated','bribed officials'], a:'used influence' },
  { type:'mc', q:'"Her proposal is a double-edged sword." It means:', options:['has advantages and risks','is very sharp','is unfair','is complex'], a:'has advantages and risks' },
  { type:'mc', q:'"They decided to bite the bullet." They:', options:['accepted a painful decision','made a rash decision','avoided the issue','consulted staff'], a:'accepted a painful decision' },
  { type:'mc', q:'"Her proposal is pie in the sky." It is:', options:['unrealistically optimistic','ambitious but feasible','expensive','risky'], a:'unrealistically optimistic' },
  // Body idioms
  { type:'mc', q:'"She had the project at her fingertips." This means:', options:['she knew it thoroughly','she was holding it','she created it','she finished it'], a:'she knew it thoroughly' },
  { type:'mc', q:'"He kept his finger on the pulse of the market." He:', options:['stayed informed of latest developments','worked in finance','controlled the market','predicted trends'], a:'stayed informed of latest developments' },
  { type:'mc', q:'"The minister put her foot down." She:', options:['refused to allow something firmly','left the meeting','stamped with authority','arrived unexpectedly'], a:'refused to allow something firmly' },
  { type:'mc', q:'"He got cold feet before signing the contract." He:', options:['lost his nerve','became ill','changed his mind late','cancelled entirely'], a:'lost his nerve' },
  { type:'mc', q:'"She turned a blind eye to the irregularities." She:', options:['deliberately ignored them','failed to notice them','reported them','investigated them'], a:'deliberately ignored them' },
  { type:'mc', q:'"He kept his cards close to his chest." He:', options:['revealed very little about his plans','played cards secretly','was secretive about everything','was dishonest'], a:'revealed very little about his plans' },
  { type:'mc', q:'"She has her hands full at the moment." She:', options:['is very busy','has two tasks','is overwhelmed','works with her hands'], a:'is very busy' },
  { type:'mc', q:'"He went behind her back." He:', options:['did something without her knowledge','physically moved behind her','deceived her openly','broke her trust publicly'], a:'did something without her knowledge' },
  { type:'mc', q:'"The CEO rules with an iron fist." The CEO:', options:['governs very strictly','is very powerful','is authoritarian but fair','uses force'], a:'governs very strictly' },
  { type:'mc', q:'"She always speaks her mind." She:', options:['says what she thinks honestly','is diplomatic','contradicts herself','speaks publicly'], a:'says what she thinks honestly' },
  // Time idioms
  { type:'mc', q:'"The deal was sealed at the eleventh hour." This means:', options:['at the last possible moment','at eleven o\'clock','after a long delay','just in time'], a:'at the last possible moment' },
  { type:'mc', q:'"The project is on borrowed time." It means:', options:['it will likely end soon','it is being financed','it needs more time','it is behind schedule'], a:'it will likely end soon' },
  { type:'mc', q:'"The minister stalled for time." She:', options:['delayed to gain more time','worked faster','requested more time','postponed the meeting'], a:'delayed to gain more time' },
  { type:'mc', q:'"In the nick of time" means:', options:['just before it was too late','exactly on time','just after the deadline','at the right moment'], a:'just before it was too late' },
  { type:'mc', q:'"She called time on the project." She:', options:['decided to end it','timed the project','scheduled a meeting','set a deadline'], a:'decided to end it' },
  // Water / sea idioms
  { type:'mc', q:'"The government is in deep water." It is:', options:['in serious trouble','underwater financially','unpopular','struggling economically'], a:'in serious trouble' },
  { type:'mc', q:'"That ship has sailed." It means:', options:['the opportunity is gone','a decision is made','it is too late to change','the plan is irreversible'], a:'the opportunity is gone' },
  { type:'mc', q:'"She tested the waters before proposing the policy." She:', options:['assessed opinion cautiously first','experimented with the policy','conducted a poll','consulted experts'], a:'assessed opinion cautiously first' },
  { type:'mc', q:'"The new manager makes waves wherever she goes." She:', options:['causes controversy and change','is very productive','attracts attention','generates conflict'], a:'causes controversy and change' },
  { type:'mc', q:'"His career has been plain sailing since the promotion." It has been:', options:['easy and without problems','steady and unexciting','rapid and successful','straightforward and predictable'], a:'easy and without problems' },
  // Fire / heat idioms
  { type:'mc', q:'"The minister came under fire from all sides." She was:', options:['criticised intensely','attacked literally','questioned firmly','pressured to resign'], a:'criticised intensely' },
  { type:'mc', q:'"The project was put on ice." It was:', options:['postponed indefinitely','cancelled permanently','delayed briefly','frozen for review'], a:'postponed indefinitely' },
  { type:'mc', q:'"She fought fire with fire." She:', options:['used the same aggressive methods as her opponents','responded to criticism with criticism','retaliated proportionately','matched the competition'], a:'used the same aggressive methods as her opponents' },
  { type:'mc', q:'"The new CEO is playing with fire." She is:', options:['taking dangerous risks','acting recklessly','making bold decisions','behaving provocatively'], a:'taking dangerous risks' },
  // Road / journey idioms
  { type:'mc', q:'"The company is at a crossroads." It is:', options:['facing a critical decision','lost','changing direction','in crisis'], a:'facing a critical decision' },
  { type:'mc', q:'"They hit a roadblock in the negotiations." They:', options:['encountered an obstacle','stopped negotiating','failed to agree','made no progress'], a:'encountered an obstacle' },
  { type:'mc', q:'"The minister paved the way for her successor." She:', options:['created conditions for success','made it easier','prepared the ground','all of the above'], a:'all of the above' },
  { type:'mc', q:'"The project has run its course." It means:', options:['it has reached a natural end','it has been running too long','it is complete','it should stop'], a:'it has reached a natural end' },
  // Animal idioms
  { type:'mc', q:'"Let the cat out of the bag." Someone:', options:['revealed a secret accidentally','disclosed information','broke a promise','made an error'], a:'revealed a secret accidentally' },
  { type:'mc', q:'"The elephant in the room" refers to:', options:['an obvious problem nobody is discussing','a large issue','an uncomfortable truth','something everyone knows'], a:'an obvious problem nobody is discussing' },
  { type:'mc', q:'"She smells a rat." She:', options:['suspects something is wrong','senses dishonesty','mistrusts someone','detects a problem'], a:'suspects something is wrong' },
  { type:'mc', q:'"He took the bull by the horns." He:', options:['dealt with the problem directly','confronted someone','made a bold decision','took charge'], a:'dealt with the problem directly' },
  { type:'mc', q:'"A dark horse" in a race is:', options:['an unexpected winner','an unknown competitor','a dangerous contender','a late entry'], a:'an unexpected winner' },
  { type:'mc', q:'"She\'s flogging a dead horse." She:', options:['wasting effort on something impossible','persevering unnecessarily','continuing after failure','refusing to give up'], a:'wasting effort on something impossible' },
  // Money / business idioms
  { type:'mc', q:'"The company cut its losses." It:', options:['stopped an activity to prevent further loss','reduced costs','accepted a small loss','dismissed staff'], a:'stopped an activity to prevent further loss' },
  { type:'mc', q:'"He drives a hard bargain." He:', options:['negotiates very firmly for the best terms','is an aggressive negotiator','is very tough to deal with','rarely compromises'], a:'negotiates very firmly for the best terms' },
  { type:'mc', q:'"The project went over budget." It:', options:['cost more than planned','failed financially','was poorly managed','exceeded expectations'], a:'cost more than planned' },
  { type:'mc', q:'"She\'s worth her weight in gold." She:', options:['is extremely valuable','is very expensive','earns a lot','is highly respected'], a:'is extremely valuable' },
  { type:'mc', q:'"The business is going to the wall." It is:', options:['about to fail/go bankrupt','struggling financially','losing market share','closing down'], a:'about to fail/go bankrupt' },
  // Additional C2 idioms (from Cambridge C2 / CPE lists)
  { type:'fill', q:'The reforms opened a can of ___ that the government is still trying to deal with.', a:'worms' },
  { type:'fill', q:'She didn\'t ___ around the bush — she told him he was being demoted.', a:'beat' },
  { type:'fill', q:'The chairman called for calm — there was no point in rocking the ___.', a:'boat' },
  { type:'fill', q:'The two rival companies have now buried the ___ and agreed to collaborate.', a:'hatchet' },
  { type:'fill', q:'The two ministers simply cannot see eye to ___ on budget policy.', a:'eye' },
  { type:'fill', q:'The inquiry was a real witch ___, targeting individuals with no solid evidence.', a:'hunt' },
  { type:'fill', q:'He tends to pass the ___ — he never takes responsibility for decisions.', a:'buck' },
  { type:'fill', q:'Following the scandal, the minister chose to keep a low ___.', a:'profile' },
  { type:'fill', q:'The proposal was put on the back ___ due to funding constraints.', a:'burner' },
  { type:'fill', q:'Her recovery has defied all ___ — nobody expected her to return.', a:'expectations' },
  { type:'fill', q:'The election campaign is now in full ___.', a:'swing' },
  { type:'fill', q:'A blessing in ___ — losing that contract freed them to pursue better work.', a:'disguise' },
  { type:'fill', q:'Her analysis really hit the nail on the ___.', a:'head' },
  { type:'fill', q:'They had to ___ the bullet and make 300 staff redundant.', a:'bite', hint:'"Bite the bullet" = accept a painful decision.' },
  { type:'fill', q:'The deal was sealed in the eleventh ___, moments before the deadline.', a:'hour' },
  { type:'fill', q:'The company has stolen a ___ on its rivals by filing the patent first.', a:'march' },
  { type:'fill', q:'The regulator moved swiftly to bring the firm to ___.', a:'heel' },
  { type:'fill', q:'The coalition is on borrowed ___ — an election is inevitable.', a:'time' },
  { type:'fill', q:'He gave his opponents the ___ of the doubt, but eventually lost patience.', a:'benefit' },
  { type:'fill', q:'That ship has ___. The opportunity to negotiate has passed.', a:'sailed' },
  { type:'fill', q:'She turned a ___ eye to the irregularities in the accounts.', a:'blind', hint:'"Turn a blind eye to" = deliberately ignore.' },
  { type:'fill', q:'He kept his cards close to his ___ during the negotiations.', a:'chest', hint:'"Keep cards close to one\'s chest" = reveal little.' },
  { type:'fill', q:'The CEO rules with an iron ___. Nobody dares challenge her.', a:'fist', hint:'"Rule with an iron fist" = govern very strictly.' },
  { type:'fill', q:'The government is in ___ water over the handling of the crisis.', a:'deep', hint:'"In deep water" = in serious trouble.' },
  { type:'fill', q:'The company cut its ___ and withdrew from the market.', a:'losses', hint:'"Cut one\'s losses" = stop an activity before further damage.' },
  { type:'fill', q:'The minister got cold ___ and refused to sign at the last moment.', a:'feet', hint:'"Get cold feet" = lose one\'s nerve.' },
  { type:'fill', q:'She tested the ___ with a few informal inquiries before proposing the policy.', a:'waters', hint:'"Test the waters" = cautiously assess opinion.' },
  { type:'fill', q:'The elephant in the ___ — nobody wants to discuss the budget deficit.', a:'room', hint:'"Elephant in the room" = obvious problem nobody discusses.' },
  { type:'fill', q:'He drives a hard ___ and rarely concedes ground in negotiations.', a:'bargain', hint:'"Drive a hard bargain" = negotiate very firmly.' },
  { type:'fill', q:'The project is at a crossroads and the board must decide which direction to take.', a:'crossroads', hint:'Already in the sentence — confirm understanding: "at a ___" (decision point).' },
],

};
