const DB_PHRASAL = {
phrasal: [
  // GET group (Astex list)
  { type:'mc', q:'"I had the feeling I wasn\'t getting the meaning ___ to the audience."', options:['across','over','through','on'], a:'across', hint:'"Get across" = make understood.' },
  { type:'mc', q:'"What are you getting ___? Could you be more direct?"', options:['at','on','over','around'], a:'at', hint:'"Get at" = hint at, imply (informal).' },
  { type:'mc', q:'"It\'s time we got ___ to some real work." Meaning: start seriously.', options:['down to','on with','round to','through with'], a:'down to', hint:'"Get down to" = start dealing with seriously.' },
  { type:'mc', q:'"They were lucky to get ___ with such light sentences."', options:['off with','out of','away from','round'], a:'off with', hint:'"Get off with" = receive a lighter punishment than deserved.' },
  { type:'mc', q:'"I couldn\'t get ___ how well she looked after the treatment."', options:['over','past','through','round'], a:'over', hint:'"Get over" = be surprised by.' },
  { type:'mc', q:'"I\'ll be glad to get this awful business ___ ___."', options:['over with','done with','out of','away from'], a:'over with', hint:'"Get over with" = finish something unpleasant.' },
  { type:'mc', q:'"Sorry, I haven\'t got ___ to fixing the tap yet."', options:['round to','down to','on to','through to'], a:'round to', hint:'"Get round to" = find time to do eventually.' },
  { type:'mc', q:'"The children are getting ___ something in the garden." (mischief)', options:['up to','on to','down to','round to'], a:'up to', hint:'"Get up to" = be doing something mischievous.' },
  { type:'fill', q:'"Sue is getting ___ very well in her new job." (progressing)', a:'on', hint:'"Get on" = make progress.' },
  { type:'fill', q:'"He must be getting on ___ seventy." (approaching an age)', a:'for', hint:'"Get on for" = approaching an age.' },
  // TAKE group (Astex list)
  { type:'mc', q:'"Don\'t be taken ___ by her apparent shyness." (deceived)', options:['in','over','on','up'], a:'in', hint:'"Take in" = deceive.' },
  { type:'mc', q:'"I know you\'re unhappy, but don\'t take it ___ ___  me!"', options:['out on','off on','up with','away from'], a:'out on', hint:'"Take it out on" = make someone else suffer for your problems.' },
  { type:'mc', q:'"Dave takes ___ the Prime Minister really well." (imitates)', options:['off','on','after','apart'], a:'off', hint:'"Take off" = imitate.' },
  { type:'mc', q:'"My grandmother has taken ___ a new lease of life since her operation."', options:['on','up','over','in'], a:'on', hint:'"Take on" = acquire (new characteristics/activities).' },
  { type:'mc', q:'"Ann has taken ___ life insurance." (arranged/signed)', options:['out','up','on','over'], a:'out', hint:'"Take out" = arrange a formal contract or subscription.' },
  { type:'mc', q:'"The army tried to take ___ the country." (seize control)', options:['over','on','up','in'], a:'over', hint:'"Take over" = seize control of.' },
  { type:'mc', q:'"You\'ll soon take ___ your new boss, I\'m sure." (like them)', options:['to','on','up with','after'], a:'to', hint:'"Take to someone" = develop appreciation for.' },
  { type:'mc', q:'"The meeting took ___ a whole morning." (occupied)', options:['up','on','over','in'], a:'up', hint:'"Take up" = occupy time or space.' },
  // LOOK group (Astex list)
  { type:'mc', q:'"If you\'re passing through Athens, ___ me ___." (visit)', options:['look up','look after','look into','look on'], a:'look up', hint:'"Look someone up" = visit someone when passing.' },
  { type:'mc', q:'"She ___ ___ her grandmother." (cared for)', options:['looked after','looked into','looked up','looked on'], a:'looked after', hint:'"Look after" = care for.' },
  { type:'mc', q:'"The police have promised to ___ ___ the problem." (investigate)', options:['look into','look after','look up','look on'], a:'look into', hint:'"Look into" = investigate.' },
  { type:'mc', q:'"We ___ ___ this town as our real home." (consider)', options:['look on','look after','look into','look up'], a:'look on', hint:'"Look on" = consider; regard as.' },
  // GO group (Astex list)
  { type:'mc', q:'"The management has gone ___ ___ its promise." (broken)', options:['back on','through with','in for','round'], a:'back on', hint:'"Go back on" = break a promise or agreement.' },
  { type:'mc', q:'"I don\'t go ___ ___ that kind of thing." (engage in habitually)', options:['in for','through with','back on','about'], a:'in for', hint:'"Go in for" = habitually engage in; enter a competition.' },
  { type:'mc', q:'"This milk has gone ___." (spoiled)', options:['off','out','over','bad'], a:'off', hint:'"Go off" = food becoming bad.' },
  { type:'mc', q:'"Something funny is going ___." (happening)', options:['on','off','round','through'], a:'on', hint:'"Go on" = happen; occur.' },
  { type:'mc', q:'"There weren\'t enough life-jackets to go ___." (be enough for all)', options:['round','on','off','about'], a:'round', hint:'"Go round" = be sufficient for everyone.' },
  { type:'mc', q:'"Nora couldn\'t go ___ ___ stealing the money when the moment came."', options:['through with','back on','in for','round to'], a:'through with', hint:'"Go through with" = complete a plan despite difficulty.' },
  // COME group (Astex list)
  { type:'mc', q:'"Let me explain how the situation came ___."', options:['about','on','off','over'], a:'about', hint:'"Come about" = happen, often gradually or by chance.' },
  { type:'mc', q:'"It all comes ___ ___ whether you are prepared to accept less money."', options:['down to','up against','in for','off'], a:'down to', hint:'"Come down to" = be essentially reducible to.' },
  { type:'mc', q:'"The government has come ___ ___ a lot of criticism over the decision."', options:['in for','up against','off','through'], a:'in for', hint:'"Come in for" = receive criticism or blame.' },
  { type:'mc', q:'"I\'m afraid that deal didn\'t come ___ after all." (succeed)', options:['off','about','through','round'], a:'off', hint:'"Come off" = succeed; happen as planned.' },
  { type:'mc', q:'"All the flowers have come ___." (appeared/bloomed)', options:['out','about','up','through'], a:'out', hint:'"Come out" = appear; emerge.' },
  { type:'mc', q:'"Look, something has come ___, and I can\'t meet you." (unexpected problem)', options:['up','about','off','through'], a:'up', hint:'"Come up" = arise unexpectedly.' },
  { type:'mc', q:'"The play didn\'t come ___ ___ expectations."', options:['up to','in for','off','about'], a:'up to', hint:'"Come up to" = reach a required standard.' },
  { type:'mc', q:'"We still haven\'t come ___ ___ a solution to the problem."', options:['up with','in for','off','up to'], a:'up with', hint:'"Come up with" = think of a plan or solution.' },
  // TURN group (Astex list)
  { type:'mc', q:'"Another company offered me a job but I turned them ___."', options:['down','away','off','back'], a:'down', hint:'"Turn down" = reject.' },
  { type:'mc', q:'"He turned ___ to be an old friend of Helen\'s." (proved to be)', options:['out','up','over','round'], a:'out', hint:'"Turn out" = prove to be in the end.' },
  { type:'mc', q:'"Thousands of fans turned ___ to welcome the team." (assembled)', options:['out','up','over','in'], a:'out', hint:'"Turn out" = assemble in numbers.' },
  { type:'mc', q:'"Don\'t worry about the missing book, it\'s bound to turn ___ sooner or later." (appear)', options:['up','out','over','around'], a:'up', hint:'"Turn up" = appear or be found unexpectedly.' },
  // MAKE group (Astex list)
  { type:'mc', q:'"The power steering makes ___ easier parking." (facilitates)', options:['for','out','up','after'], a:'for', hint:'"Make for" = contribute to; facilitate.' },
  { type:'mc', q:'"The thief made ___ ___ a valuable necklace." (escaped with)', options:['off with','out with','up for','after'], a:'off with', hint:'"Make off with" = steal and escape with.' },
  { type:'mc', q:'"Tim made ___ that he hadn\'t seen the No Smoking sign." (pretended)', options:['out','up','for','off'], a:'out', hint:'"Make out" = pretend.' },
  { type:'mc', q:'"I couldn\'t quite make ___ what the notice said." (decipher)', options:['out','up','for','off'], a:'out', hint:'"Make out" = see or understand with difficulty.' },
  { type:'mc', q:'"Janet is really odd. I can\'t make her ___." (understand her)', options:['out','up','for','off'], a:'out', hint:'"Make someone out" = understand someone\'s character.' },
  { type:'mc', q:'"I think you made ___ the whole story!" (invented)', options:['up','out','for','off'], a:'up', hint:'"Make up" = invent a story.' },
  { type:'mc', q:'"Our success makes ___ ___ all the hard times." (compensates)', options:['up for','out of','off with','for'], a:'up for', hint:'"Make up for" = compensate.' },
  // SET group (Astex list)
  { type:'mc', q:'"We must set ___ re-organising the office." (begin)', options:['about','out','in','up'], a:'about', hint:'"Set about" = begin doing something.' },
  { type:'mc', q:'"I think this rain has set ___ for the day." (established itself)', options:['in','out','up','about'], a:'in', hint:'"Set in" = become established (of weather/conditions).' },
  { type:'mc', q:'"This document sets ___ all the Union demands." (explains in writing)', options:['out','up','in','about'], a:'out', hint:'"Set out" = explain or present in writing.' },
  { type:'mc', q:'"Sue set ___ to write a biography but it became a novel." (aimed/began)', options:['out','about','up','in'], a:'out', hint:'"Set out" = begin with a particular aim.' },
  { type:'mc', q:'"An inquiry into the accident has been set ___." (established)', options:['up','out','in','about'], a:'up', hint:'"Set up" = establish; create.' },
  { type:'mc', q:'"We were set ___ by a gang of hooligans." (attacked)', options:['upon','out','up','in'], a:'upon', hint:'"Set upon" = attack.' },
  // GIVE group (Astex list)
  { type:'mc', q:'"His false identity papers gave him ___." (betrayed/revealed)', options:['away','out','up','over'], a:'away', hint:'"Give away" = reveal something secret; betray.' },
  { type:'mc', q:'"The cheese had begun to give ___ a strange smell." (emit)', options:['off','out','away','over'], a:'off', hint:'"Give off" = emit (smell, heat, light).' },
  { type:'mc', q:'"When our money gave ___ we had to borrow some." (ran out)', options:['out','up','away','over'], a:'out', hint:'"Give out" = be exhausted; run out.' },
  { type:'mc', q:'"The rest of the time was given ___ to playing cards." (devoted to)', options:['over','away','out','up'], a:'over', hint:'"Give over" = devote to an activity.' },
  { type:'mc', q:'"Why don\'t you give ___? You are getting on my nerves." (stop)', options:['over','up','away','out'], a:'over', hint:'"Give over" = stop (British informal).' },
  { type:'mc', q:'"The escaped prisoner gave herself ___." (surrendered)', options:['up','over','away','out'], a:'up', hint:'"Give up" = surrender.' },
  { type:'mc', q:'"They gave ___ gambling." (stopped the habit)', options:['up','over','away','out'], a:'up', hint:'"Give up" = abandon a habit or activity.' },
  // CUT group (Astex list)
  { type:'mc', q:'"My Dad has high cholesterol, so he has cut ___ eggs." (stopped eating)', options:['out','back','off','up'], a:'out', hint:'"Cut out" = stop consuming or doing.' },
  { type:'mc', q:'"You eat too much salt, you should cut ___ on salty foods." (reduce)', options:['back','out','off','down'], a:'back', hint:'"Cut back" = reduce the amount.' },
  { type:'mc', q:'"He cut all the fat ___." (removed by cutting)', options:['off','out','up','back'], a:'off', hint:'"Cut off" = remove by cutting.' },
  { type:'mc', q:'"He cut the pie ___ into equal slices." (divided)', options:['up','out','off','back'], a:'up', hint:'"Cut up" = cut into pieces.' },
  // BRING group (Astex list)
  { type:'mc', q:'"The crisis was brought ___ by Brenda\'s resignation." (caused)', options:['about','on','in','off'], a:'about', hint:'"Bring about" = cause to happen.' },
  { type:'mc', q:'"Against all odds, she brought ___ a remarkable turnaround." (succeeded)', options:['off','about','in','on'], a:'off', hint:'"Bring off" = succeed in doing something difficult.' },
  { type:'mc', q:'"It took weeks to bring the board ___ to the new strategy." (persuade)', options:['round','in','about','on'], a:'round', hint:'"Bring round" = persuade.' },
  { type:'mc', q:'"The investigation brought ___ ___ a pattern of systematic fraud." (revealed)', options:['to light','about','off','in'], a:'to light', hint:'"Bring to light" = reveal something hidden.' },
  { type:'mc', q:'"She raised the issue by bringing it ___ at the meeting." (mentioned)', options:['up','about','in','on'], a:'up', hint:'"Bring up" = raise a topic for discussion.' },
  { type:'mc', q:'"New evidence has been brought ___ to support the theory." (introduced)', options:['in','about','off','up'], a:'in', hint:'"Bring in" = introduce; involve.' },
  // PUT group
  { type:'mc', q:'"The board put the decision ___ until the next quarterly meeting." (postponed)', options:['off','back','up','over'], a:'off', hint:'"Put off" = postpone.' },
  { type:'mc', q:'"Several candidates were put ___ for the position." (proposed)', options:['forward','up','in','out'], a:'forward', hint:'"Put forward" = propose or present.' },
  { type:'mc', q:'"Who signed ___ on this expenditure?" (formally approved)', options:['off','out','up','over'], a:'off', hint:'"Sign off on" = give formal approval.' },
  { type:'mc', q:'"The company put ___ a statement denying the allegations." (issued)', options:['out','off','forward','in'], a:'out', hint:'"Put out" = issue; release.' },
  { type:'mc', q:'"She struggled to put her argument ___." (communicate clearly)', options:['across','forward','out','over'], a:'across', hint:'"Put across" = communicate an idea effectively.' },
  // HOLD group
  { type:'mc', q:'"There is nothing to hold ___ further investment." (prevent)', options:['back','off','up','out'], a:'back', hint:'"Hold back" = restrain or prevent.' },
  { type:'mc', q:'"The union held ___ for a better deal." (refused to yield)', options:['out','back','off','on'], a:'out', hint:'"Hold out" = resist; refuse to concede.' },
  { type:'mc', q:'"The company managed to hold ___ its rivals for another quarter." (resist)', options:['off','out','back','on'], a:'off', hint:'"Hold off" = resist an attack or competitor.' },
  { type:'mc', q:'"Ideology continues to hold ___ over economic policy." (have power)', options:['sway','back','out','off'], a:'sway', hint:'"Hold sway" = have great power or influence.' },
  // WORK group
  { type:'mc', q:'"The situation worked ___ in our favour in the end." (resolved itself well)', options:['out','off','up','over'], a:'out', hint:'"Work out" = resolve itself; also = exercise.' },
  { type:'mc', q:'"We need to work ___ a solution that satisfies all parties." (develop)', options:['out','up','over','in'], a:'out', hint:'"Work out" = develop/figure out.' },
  { type:'mc', q:'"She has worked her way ___ to become director." (risen through effort)', options:['up','out','in','over'], a:'up', hint:'"Work up" = rise through hard work.' },
  { type:'mc', q:'"The press have been working ___ the minister over the new policy." (scrutinising/pressuring)', options:['over','up','out','in'], a:'over', hint:'"Work over" = subject to intense scrutiny or pressure.' },
  // FALL group
  { type:'mc', q:'"The coalition ___ ___ over the budget dispute." (disintegrated)', options:['fell apart','fell out','fell through','fell back'], a:'fell apart', hint:'"Fall apart" = disintegrate.' },
  { type:'mc', q:'"The company ___ ___ of the competition regulator." (violated their rules)', options:['fell foul','fell out','fell apart','fell back'], a:'fell foul', hint:'"Fall foul of" = come into conflict with a rule or authority.' },
  { type:'mc', q:'"The merger ___ ___ at the last moment." (failed to happen)', options:['fell through','fell apart','fell out','fell back'], a:'fell through', hint:'"Fall through" = fail to happen.' },
  { type:'mc', q:'"When the system failed, staff had to ___ ___ manual processes." (resort to)', options:['fall back on','fall foul of','fall through','fall apart'], a:'fall back on', hint:'"Fall back on" = use as a last resort.' },
  // CARRY group
  { type:'mc', q:'"The government carried ___ a radical reshuffle." (performed)', options:['out','on','over','through'], a:'out', hint:'"Carry out" = perform a task.' },
  { type:'mc', q:'"Despite the setbacks, the project carried ___." (continued)', options:['on','out','over','through'], a:'on', hint:'"Carry on" = continue.' },
  { type:'mc', q:'"She was determined to carry ___ the reforms she had promised." (complete)', options:['through','out','on','over'], a:'through', hint:'"Carry through" = complete despite difficulties.' },
  { type:'mc', q:'"The budget surplus was carried ___ to the next financial year." (transferred)', options:['over','out','on','through'], a:'over', hint:'"Carry over" = transfer to the next period.' },
  // DRAW group
  { type:'mc', q:'"The lawyers drew ___ a comprehensive contract." (prepared)', options:['up','on','in','out'], a:'up', hint:'"Draw up" = prepare a formal document.' },
  { type:'mc', q:'"Her speech drew ___ decades of frontline experience." (used)', options:['on','up','in','out'], a:'on', hint:'"Draw on" = use as a resource.' },
  { type:'mc', q:'"The report draws a clear ___ between the two phenomena." (distinction)', options:['distinction','conclusion','line','parallel'], a:'distinction', hint:'"Draw a distinction" = identify and emphasise a difference.' },
  // STEP group
  { type:'mc', q:'"The chairman agreed to step ___ after the vote of no confidence." (resign)', options:['down','back','aside','away'], a:'down', hint:'"Step down" = resign from a position.' },
  { type:'mc', q:'"She asked the board to step ___ from the day-to-day running." (disengage)', options:['back','down','aside','away'], a:'back', hint:'"Step back" = disengage; stop being involved.' },
  // Additional high-frequency C2 phrasal verbs
  { type:'mc', q:'"The scandal ___ ___ after a whistleblower leaked documents." (exploded into public view)', options:['blew up','blew over','blew out','blew in'], a:'blew up', hint:'"Blow up" = suddenly become public or serious.' },
  { type:'mc', q:'"The controversy eventually ___." (faded and was forgotten)', options:['blew over','blew up','blew out','blew away'], a:'blew over', hint:'"Blow over" = pass and be forgotten.' },
  { type:'mc', q:'"It all ___ ___ one fundamental question." (reduces to)', options:['boils down to','comes down to','both a and b','adds up to'], a:'both a and b', hint:'"Boil down to" and "come down to" both mean reduce to the essential point.' },
  { type:'mc', q:'"After weeks of resistance, the government finally ___ ___." (yielded)', options:['caved in','backed down','both a and b','gave way'], a:'both a and b', hint:'"Cave in" and "back down" both mean yield to pressure.' },
  { type:'mc', q:'"The company is ___ ___ into renewable energy." (expanding)', options:['branching out','moving in','breaking out','pushing into'], a:'branching out', hint:'"Branch out" = expand into a new area.' },
  { type:'mc', q:'"The list of candidates was ___ ___ to three." (reduced)', options:['narrowed down','whittled down','both a and b','cut down'], a:'both a and b', hint:'"Narrow down" and "whittle down" both mean gradually reduce.' },
  { type:'mc', q:'"Coal subsidies are being ___ ___ across the EU." (removed gradually)', options:['phased out','wound down','both a and b','rolled back'], a:'phased out', hint:'"Phase out" = withdraw gradually over a period.' },
  { type:'mc', q:'"The vaccine was ___ ___ across the country within months." (deployed widely)', options:['rolled out','phased in','both a and b','launched'], a:'rolled out', hint:'"Roll out" = deploy on a large scale.' },
  { type:'mc', q:'"The possibility of further cuts has not been ___ ___." (eliminated)', options:['ruled out','closed off','written off','excluded'], a:'ruled out', hint:'"Rule out" = eliminate as a possibility.' },
  { type:'mc', q:'"The government intends to ___ ___ with the reforms regardless." (continue despite opposition)', options:['press ahead','go ahead','carry on','all of the above'], a:'all of the above', hint:'All three are correct; "press ahead" is most formal and emphatic.' },
  { type:'mc', q:'"The inquiry ___ ___ the extent of the corruption." (revealed completely)', options:['laid bare','brought to light','both a and b','uncovered'], a:'both a and b', hint:'"Lay bare" and "bring to light" both mean reveal hidden information.' },
  { type:'mc', q:'"She ___ ___ for her principles despite enormous pressure." (defended them)', options:['stood up','spoke out','both a and b','held firm'], a:'both a and b', hint:'"Stand up for" = defend; "speak out" = express views publicly despite risk.' },
  { type:'mc', q:'"The state is accused of ___ ___ unviable industries." (artificially supporting)', options:['propping up','bailing out','holding up','both a and b'], a:'propping up', hint:'"Prop up" = support something that would otherwise fail.' },
  { type:'fill', q:'"His initial enthusiasm quickly wore ___."', a:'off', hint:'"Wear off" = gradually diminish.' },
  { type:'fill', q:'"The rumours were eventually played ___ by the spokesperson."', a:'down', hint:'"Play down" = minimise the significance.' },
  { type:'fill', q:'"She came ___ to accepting the new terms after months of resistance."', a:'round', hint:'"Come round to" = gradually accept.' },
  { type:'fill', q:'"The reform programme came up ___ fierce resistance from lobbyists."', a:'against', hint:'"Come up against" = encounter an obstacle.' },
  { type:'fill', q:'"The company managed to ride ___ the recession through careful management."', a:'out', hint:'"Ride out" = endure a difficult period.' },
  { type:'fill', q:'"The minister was asked to account ___ the discrepancy in the figures."', a:'for', hint:'"Account for" = explain.' },
  { type:'fill', q:'"Production ground to a ___  during the strike."', a:'halt', hint:'"Grind to a halt" = stop completely.' },
  { type:'fill', q:'"The two sides finally hammered ___ a deal after three days of talks."', a:'out', hint:'"Hammer out" = reach through prolonged negotiation.' },
  { type:'fill', q:'"After the crisis, the company took ___ of its position and restructured."', a:'stock', hint:'"Take stock of" = carefully assess.' },
  { type:'fill', q:'"The inquiry laid ___ the extent of the corruption within the department."', a:'bare', hint:'"Lay bare" = reveal completely.' },
  { type:'fill', q:'"The judge handed ___ a custodial sentence of five years."', a:'down', hint:'"Hand down" a sentence = deliver formally.' },
  { type:'fill', q:'"By investing in multiple markets, the fund was hedging its ___."', a:'bets', hint:'"Hedge one\'s bets" = protect against risk.' },
  { type:'fill', q:'"The coalition began to come ___ after the second election defeat."', a:'apart', hint:'"Come apart" = disintegrate.' },
  { type:'fill', q:'"Word quickly got ___ about the planned redundancies."', a:'around', hint:'"Get around" (of news) = spread.' },
  { type:'fill', q:'"Inflation appears to have levelled ___ at around 3%."', a:'off', hint:'"Level off" = stabilise.' },
  { type:'fill', q:'"The government has been accused of propping ___ unviable industries."', a:'up', hint:'"Prop up" = support something that would otherwise fail.' },
  { type:'fill', q:'"She was quick to pick ___ the tension in the room."', a:'up on', hint:'"Pick up on" = notice something subtle.' },
  { type:'fill', q:'"The protests died ___ once the law was repealed."', a:'down', hint:'"Die down" = become less intense; subside.' },
  { type:'fill', q:'"He drew ___ his decades of experience when writing the report."', a:'on', hint:'"Draw on" = use as a resource.' },
  { type:'fill', q:'"She has worked her way ___ to become director."', a:'up', hint:'"Work up" = rise through hard work.' },
  { type:'fill', q:'"The chairman agreed to step ___ after the vote of no confidence."', a:'down', hint:'"Step down" = resign from a position.' },
  { type:'fill', q:'"New standards will be phased ___ over a five-year period."', a:'in', hint:'"Phase in" = introduce gradually.' },
  { type:'fill', q:'"The minister spent the conference fending ___ questions about the scandal."', a:'off', hint:'"Fend off" = defend against attack or questions.' },
  { type:'fill', q:'"The two sides tried to smooth ___ their differences at the summit."', a:'over', hint:'"Smooth over" = reduce tension; make less serious.' },
  { type:'fill', q:'"The old regulations have been swept ___ and replaced with new ones."', a:'away', hint:'"Sweep away" = abolish or remove completely.' },
  { type:'fill', q:'"The government is reluctant to reopen issues that have been swept ___ the carpet."', a:'under', hint:'"Sweep under the carpet" = conceal a problem.' },
  { type:'fill', q:'"She called ___ to cancel the meeting an hour before it was due to start."', a:'off', hint:'"Call off" = cancel.' },
  { type:'fill', q:'"The company\'s poor results have been brushed ___ by management."', a:'aside', hint:'"Brush aside" = dismiss as unimportant.' },
  { type:'fill', q:'"The minister tried to play ___ the severity of the budget shortfall."', a:'down', hint:'"Play down" = make seem less important.' },
  { type:'fill', q:'"The opposition is trying to whip ___ support for a vote of no confidence."', a:'up', hint:'"Whip up" = rapidly generate (support, enthusiasm).' },

// ── CALL group (complete) ────────────────────────────────────────────────
  { type:'mc', q:'"The baby is called ___ his grandfather." Meaning: named after.', options:['after','for','on','upon'], a:'after', hint:'"Call after" = give the same name as another person.' },
  { type:'mc', q:'"The train calls ___ Oxbridge and Glenville." Meaning: stops briefly.', options:['at','in','by','on'], a:'at', hint:'"Call at" = stop briefly at a place (of trains/ships).' },
  { type:'mc', q:'"The doctor was called ___ for an emergency." Meaning: asked to leave.', options:['away','out','in','off'], a:'away', hint:'"Call away" = request someone to leave for something urgent.' },
  { type:'mc', q:'"I\'ll call you ___ as soon as possible." Meaning: return the call.', options:['back','in','up','on'], a:'back', hint:'"Call back" = return a phone call.' },
  { type:'mc', q:'"Tom said he would call ___ her at 8 o\'clock." Meaning: collect her.', options:['for','on','in','by'], a:'for', hint:'"Call for" = go to collect someone.' },
  { type:'mc', q:'"The authorities called ___ an investigation." Meaning: demanded one.', options:['for','in','on','off'], a:'for', hint:'"Call for" = demand that something be done.' },
  { type:'mc', q:'"The job calls ___ excellent computer skills." Meaning: requires them.', options:['for','on','upon','in'], a:'for', hint:'"Call for" = require; make necessary.' },
  { type:'mc', q:'"He called ___ the plumber to repair the leak." Meaning: asked to come.', options:['in','for','on','out'], a:'in', hint:'"Call in" = ask someone to come and do a job.' },
  { type:'mc', q:'"Jack called ___ ___ his parents yesterday." Meaning: visited briefly.', options:['in on','over to','round to','by at'], a:'in on', hint:'"Call in on" = pay a brief visit to someone.' },
  { type:'mc', q:'"I now call ___ the President to address the assembly." Meaning: formally invite.', options:['on','for','upon','in'], a:'on', hint:'"Call on/upon" = formally invite or request someone to do something.' },
  { type:'mc', q:'"He called ___ my name but I didn\'t answer." Meaning: shouted it.', options:['out','on','after','up'], a:'out', hint:'"Call out" = shout or announce loudly.' },
  { type:'mc', q:'"The nurse said she would call ___ to see my mother." Meaning: visit.', options:['round','in','by','over'], a:'round', hint:'"Call round" = visit someone at their home (BrE).' },
  { type:'mc', q:'"My grandfather was called ___ to active duty in 1940." Meaning: conscripted.', options:['up','in','out','on'], a:'up', hint:'"Call up" = conscript into the military; also = phone.' },
  { type:'fill', q:'"The picnic was called ___ due to the storm." (cancelled)', a:'off', hint:'"Call off" = cancel.' },
  { type:'fill', q:'"He called ___ to return my message but I missed him." (phoned back)', a:'back', hint:'"Call back" = return a phone call.' },
  { type:'fill', q:'"The job calls ___ a high level of attention to detail." (requires)', a:'for', hint:'"Call for" = require; make necessary.' },
  { type:'fill', q:'"I now call ___ the Prime Minister to address the house." (formally invite)', a:'on', hint:'"Call on/upon" = formally invite someone to speak or act.' },
  { type:'fill', q:'"My grandfather was called ___ to serve in the war." (conscripted)', a:'up', hint:'"Call up" = conscript into the military.' },

// ── PICK group (complete) ────────────────────────────────────────────────
  { type:'mc', q:'"The weather seems to be picking ___." Meaning: improving.', options:['up','on','out','off'], a:'up', hint:'"Pick up" = improve (of weather, trade, health).' },
  { type:'mc', q:'"Mauro picks ___ his food. He eats like a bird." Meaning: eats slowly/little.', options:['at','on','over','through'], a:'at', hint:'"Pick at" = eat very slowly or reluctantly.' },
  { type:'mc', q:'"You have a mosquito bite — you shouldn\'t pick ___ it." Meaning: scratch.', options:['at','on','over','off'], a:'at', hint:'"Pick at" = repeatedly touch or scratch.' },
  { type:'mc', q:'"Toni picked the hairs ___ her sweater one by one." Meaning: removed them.', options:['off','at','out','away'], a:'off', hint:'"Pick off" = remove one by one.' },
  { type:'mc', q:'"Teenagers always pick ___ the new kid in school." Meaning: bully/target.', options:['on','at','out','over'], a:'on', hint:'"Pick on" = repeatedly single out someone to bully or criticise.' },
  { type:'mc', q:'"I picked ___ a little Korean when I lived in Seoul." Meaning: learned informally.', options:['up','out','on','at'], a:'up', hint:'"Pick up" = acquire a skill or language through experience.' },
  { type:'mc', q:'"Miami Beach really picks ___ in March because of Spring Break." Meaning: gets busier.', options:['up','on','out','over'], a:'up', hint:'"Pick up" = become busier or more active.' },
  { type:'mc', q:'"Larry always picks me ___ when I fly into Philadelphia." Meaning: collects by car.', options:['up','on','out','over'], a:'up', hint:'"Pick up" = collect someone in a vehicle.' },
  { type:'mc', q:'"Anastasia picked ___ our tab at the bar." Meaning: paid for everyone.', options:['up','on','out','over'], a:'up', hint:'"Pick up" = pay for something on someone\'s behalf.' },
  { type:'mc', q:'"I told Gina to pick ___ a new pair of shoes for her birthday." Meaning: choose.', options:['out','up','on','off'], a:'out', hint:'"Pick out" = choose or select.' },
  { type:'fill', q:'"I ___ up a little Japanese while I was living in Osaka." (learned informally)', a:'picked', hint:'"Pick up" a language = learn through experience, not formal study.' },
  { type:'fill', q:'"Stop picking ___ me! I haven\'t done anything wrong." (targeting unfairly)', a:'on', hint:'"Pick on" = bully or repeatedly criticise someone.' },
  { type:'fill', q:'"She picked ___ the winning design from hundreds of entries." (selected)', a:'out', hint:'"Pick out" = choose; select.' },

// ── CARRY group (missing variants) ──────────────────────────────────────
  { type:'mc', q:'"My son normally gets a little carried ___ on his birthday." Meaning: overexcited.', options:['away','on','out','off'], a:'away', hint:'"Get carried away" = lose control due to excitement.' },
  { type:'mc', q:'"Mary carried ___ a gold medal in the swimming championship." Meaning: won.', options:['off','away','out','on'], a:'off', hint:'"Carry off" = win a prize; succeed at something difficult.' },

// ── BE group (complete — was almost entirely missing) ────────────────────
  { type:'mc', q:'"What\'s he after? Is he looking for proof?" — "Be after" means:', options:['trying to get/find something','chasing someone literally','making an inquiry','investigating formally'], a:'trying to get/find something', hint:'"Be after" = want or be trying to obtain.' },
  { type:'mc', q:'"I must say I\'m against the idea." — "Be against" means:', options:['to oppose','to dislike','to disagree with','all of the above'], a:'all of the above', hint:'"Be against" = oppose or be in disagreement with.' },
  { type:'mc', q:'"Jack will be ___ soon. He\'s on his way." Meaning: will arrive.', options:['along','in','over','round'], a:'along', hint:'"Be along" = arrive; be there soon.' },
  { type:'mc', q:'"She is ___ today. She has gone to London." Meaning: away for a period.', options:['away','out','off','gone'], a:'away', hint:'"Be away" = absent; away from home or work for a period.' },
  { type:'mc', q:'"John is a bit ___ today — the news was bad." Meaning: depressed.', options:['down','off','low','out'], a:'down', hint:'"Be down" = feel depressed or low.' },
  { type:'mc', q:'"Oil prices were ___ today." Meaning: had decreased.', options:['down','off','under','low'], a:'down', hint:'"Be down" = have decreased (of prices, numbers).' },
  { type:'mc', q:'"Why is Charlie so down ___ the new recruit?" Meaning: disapproving of.', options:['on','with','about','at'], a:'on', hint:'"Be down on" = be critical of; disapprove of.' },
  { type:'mc', q:'"My mother is ___ ___ a bad cold." Meaning: ill with.', options:['down with','in for','out with','up with'], a:'down with', hint:'"Be down with" = be ill with a disease.' },
  { type:'mc', q:'"I think we are ___ ___ snow today." Meaning: likely to experience.', options:['in for','up for','out for','down for'], a:'in for', hint:'"Be in for" = be about to experience something (usually unpleasant).' },
  { type:'mc', q:'"Alex is ___ ___ the project too." Meaning: participating.', options:['in on','up for','out of','into'], a:'in on', hint:'"Be in on" = be involved in or aware of a plan.' },
  { type:'mc', q:'"He\'s ___ sports and she\'s ___ politics." Meaning: enthusiastic about.', options:['into','in for','onto','up for'], a:'into', hint:'"Be into" = be very interested in or enthusiastic about.' },
  { type:'mc', q:'"I\'m ___! I\'ve got a plane to catch." Meaning: leaving now.', options:['off','out','away','gone'], a:'off', hint:'"Be off" = be leaving; depart.' },
  { type:'mc', q:'"The driver was ___ drugs at the time of the accident." Meaning: taking them.', options:['on','in','with','under'], a:'on', hint:'"Be on" = be taking (medication, drugs).' },
  { type:'mc', q:'"What are you ___ ___? I don\'t understand what you mean." (BrE informal)', options:['on about','in for','into','onto'], a:'on about', hint:'"Be on about" = be talking about; what someone means.' },
  { type:'mc', q:'"My colleague must be ___ ___ something exciting." Meaning: have discovered.', options:['onto','into','in on','up to'], a:'onto', hint:'"Be onto" = have discovered or be close to discovering something.' },
  { type:'mc', q:'"Where\'s Peter? He\'s ___ today." Meaning: briefly away from work.', options:['out','away','off','gone'], a:'out', hint:'"Be out" = be away from home or work for a short time.' },
  { type:'mc', q:'"We\'re ___ ___ coffee, I\'m afraid." Meaning: have no more left.', options:['out of','short of','low on','all of the above'], a:'all of the above', hint:'"Be out of" = have no remaining supply of something.' },
  { type:'mc', q:'"He\'s ___ ___ win the match at all costs." Meaning: determined to.', options:['out to','up to','on to','in for'], a:'out to', hint:'"Be out to" = be determined to achieve something.' },
  { type:'mc', q:'"Tom was ___ at the crack of dawn!" Meaning: awake and active.', options:['up','on','out','away'], a:'up', hint:'"Be up" = be awake and out of bed.' },
  { type:'mc', q:'"The interest rates are ___ again." Meaning: have increased.', options:['up','on','over','out'], a:'up', hint:'"Be up" = have increased (of prices, rates, numbers).' },
  { type:'mc', q:'"It\'s ___ ___ the government to find a solution." Meaning: their responsibility.', options:['up to','down to','in for','out to'], a:'up to', hint:'"Be up to" = be the responsibility or decision of.' },
  { type:'fill', q:'"What are those kids up ___?" Meaning: what mischief are they doing?', a:'to', hint:'"Be up to" = be doing something secret or mischievous.' },
  { type:'fill', q:'"I\'m ___! I\'ve got a plane to catch." (departing)', a:'off', hint:'"Be off" = be leaving now.' },
  { type:'fill', q:'"We\'re out ___ coffee, I\'m afraid." (have no more)', a:'of', hint:'"Be out of" = have no remaining supply.' },
  { type:'fill', q:'"She is ___ medication for her condition." (taking it)', a:'on', hint:'"Be on" = be taking medication.' },

// ── SEE group (complete — was entirely missing) ──────────────────────────
  { type:'mc', q:'"I saw ___ his intentions at once." Meaning: understood his true motives.', options:['through','into','past','over'], a:'through', hint:'"See through" = perceive the true nature of; not be deceived.' },
  { type:'mc', q:'"I\'ll see ___ whether we can manage it." Meaning: consider and arrange.', options:['about','into','to','over'], a:'about', hint:'"See about" = deal with; make arrangements for.' },
  { type:'mc', q:'"Her secretary saw me ___ her office." Meaning: accompanied me inside.', options:['into','through','to','in'], a:'into', hint:'"See into" = accompany someone into a place.' },
  { type:'mc', q:'"A cat came in the garden but the dog soon saw it ___." Meaning: chased away.', options:['off','out','away','through'], a:'off', hint:'"See off" = chase away an intruder or unwanted visitor.' },
  { type:'mc', q:'"I went to the station to see them ___." Meaning: say goodbye at departure.', options:['off','out','away','through'], a:'off', hint:'"See off" = go to a departure point to say goodbye.' },
  { type:'mc', q:'"I\'ll get your coats and see you ___." Meaning: accompany to the exit.', options:['out','off','away','through'], a:'out', hint:'"See out" = accompany a visitor to the door or exit.' },
  { type:'mc', q:'"The team had difficulties but saw the project ___ successfully." Meaning: completed.', options:['through','out','off','over'], a:'through', hint:'"See through" = continue to the end despite difficulties.' },
  { type:'mc', q:'"The police quickly saw ___ her disguise and arrested her." Meaning: detected.', options:['through','into','past','beyond'], a:'through', hint:'"See through" = detect that someone is lying or disguising something.' },
  { type:'mc', q:'"He saw ___ the arrangements and everything ran smoothly." Meaning: handled.', options:['to','about','into','over'], a:'to', hint:'"See to" = deal with; take responsibility for.' },
  { type:'fill', q:'"He saw ___ her intentions and refused to cooperate." (understood the truth)', a:'through', hint:'"See through" = perceive the truth behind deception.' },
  { type:'fill', q:'"Don\'t worry — I\'ll see ___ everything before the meeting." (deal with)', a:'to', hint:'"See to" = deal with; take responsibility for.' },
  { type:'fill', q:'"I went to the airport to see them ___." (say goodbye)', a:'off', hint:'"See off" = go to say goodbye at a departure point.' },

// ── KEEP group (complete — was almost entirely missing) ──────────────────
  { type:'mc', q:'"Well done! Keep ___ the good work!" Meaning: continue at this level.', options:['up','at','on','to'], a:'up', hint:'"Keep up" = maintain the same good level.' },
  { type:'mc', q:'"I have no idea why they keep ___ this piece of junk." Meaning: continue to have.', options:['around','on','up','at'], a:'around', hint:'"Keep around" = continue to have something available.' },
  { type:'mc', q:'"Jill kept ___ the puzzle until she put all the pieces together." Meaning: persisted.', options:['at','on','up','to'], a:'at', hint:'"Keep at" = persist with something difficult.' },
  { type:'mc', q:'"The warehouse has a guard dog to keep ___ thieves." Meaning: deter.', options:['away','out','off','back'], a:'away', hint:'"Keep away" = prevent from coming near.' },
  { type:'mc', q:'"The police kept ___ the crowd by blocking off the street." Meaning: prevented advancing.', options:['back','away','out','off'], a:'back', hint:'"Keep back" = prevent from moving forward.' },
  { type:'mc', q:'"Keep ___ the noise! I\'m trying to sleep." Meaning: reduce/suppress.', options:['down','off','back','to'], a:'down', hint:'"Keep down" = suppress; reduce in volume or amount.' },
  { type:'mc', q:'"I couldn\'t keep myself ___ eating the last piece of cake." Meaning: stop myself.', options:['from','off','away from','out of'], a:'from', hint:'"Keep from" = stop oneself from doing something.' },
  { type:'mc', q:'"She kept him ___ because he had a high temperature." Meaning: made him stay inside.', options:['in','back','away','down'], a:'in', hint:'"Keep in" = prevent from going out.' },
  { type:'mc', q:'"The reporter kept ___ any topic of the recent scandal." Meaning: avoided it.', options:['off','away from','to','back from'], a:'off', hint:'"Keep off" = avoid a topic or subject; stay away from.' },
  { type:'mc', q:'"Let\'s keep ___ hiking — it\'s such a beautiful day." Meaning: continue.', options:['on','up','at','going'], a:'on', hint:'"Keep on" = continue doing something.' },
  { type:'mc', q:'"We were kept ___ of the club because we were too young." Meaning: not admitted.', options:['out','away','back','off'], a:'out', hint:'"Keep out" = prevent from entering.' },
  { type:'mc', q:'"Let\'s keep ___ the plan. I don\'t want to make any changes." Meaning: follow it.', options:['to','up','on','at'], a:'to', hint:'"Keep to" = adhere to; not deviate from.' },
  { type:'fill', q:'"Keep ___ the good work!" (continue at the same level)', a:'up', hint:'"Keep up" = maintain the same good level.' },
  { type:'fill', q:'"She kept ___ the puzzle for hours until she solved it." (persisted)', a:'at', hint:'"Keep at" = continue despite difficulty.' },
  { type:'fill', q:'"The police kept ___ the crowd with barriers." (prevented from advancing)', a:'back', hint:'"Keep back" = prevent from moving forward.' },
  { type:'fill', q:'"Let\'s keep ___ the original plan and not deviate." (adhere to)', a:'to', hint:'"Keep to" = adhere to; not deviate from.' },
  { type:'fill', q:'"Keep the noise ___! I\'m trying to concentrate." (suppress/reduce)', a:'down', hint:'"Keep down" = suppress; keep at a low level.' },

// ── Missing variants from other groups ──────────────────────────────────
  { type:'mc', q:'"Sitting in the damp brought ___ his rheumatism." Meaning: caused it.', options:['on','about','out','in'], a:'on', hint:'"Bring on" = cause an illness or problem to develop.' },
  { type:'mc', q:'"You have brought this ___ yourself." Meaning: caused your own problem.', options:['on','about','in','upon'], a:'on', hint:'"Bring on/upon oneself" = cause something unpleasant to happen to yourself.' },
  { type:'mc', q:'"A dog came ___ me when I started running." Meaning: chased me.', options:['after','at','on','for'], a:'after', hint:'"Come after" = follow; pursue; chase.' },
  { type:'mc', q:'"She is going ___ a great job at the tech company." Meaning: pursuing.', options:['after','for','into','at'], a:'after', hint:'"Go after" = pursue; try to obtain or achieve.' },
  { type:'mc', q:'"She made ___ the bus but could not reach it." Meaning: ran towards.', options:['after','for','off','on'], a:'after', hint:'"Make after" = run or move towards in pursuit.' },
  { type:'mc', q:'"Look ___ the term online." Meaning: search for information.', options:['up','into','out','over'], a:'up', hint:'"Look up" = search for information in a reference source.' },
  { type:'mc', q:'"She took the envelope ___." Meaning: left with it; removed it.', options:['away','off','out','over'], a:'away', hint:'"Take away" = remove; take with you when leaving.' },
  { type:'mc', q:'"After ten days the ship was given ___ for lost." Meaning: assumed to be.', options:['up','over','away','out'], a:'up', hint:'"Give up" = accept as lost, impossible, or hopeless.' },
  { type:'mc', q:'"I\'ve set ___ the refreshments in the hall." Meaning: arranged/prepared them.', options:['out','up','in','about'], a:'out', hint:'"Set out" = arrange or lay out items in preparation.' },
],

};
