const DB_PREPOSITIONS = {
prepositions: [
  // Verb + preposition
  { type:'fill', q:'She was completely taken aback ___ the harshness of the criticism.', a:'by' },
  { type:'fill', q:'The policy is tantamount ___ an admission of guilt.', a:'to', hint:'"Tantamount to" = equivalent to.' },
  { type:'fill', q:'His argument is premised ___ a fundamental misreading of the data.', a:'on' },
  { type:'fill', q:'She remained adamant ___ her refusal to negotiate.', a:'about' },
  { type:'fill', q:'He was charged ___ embezzlement and fraud.', a:'with' },
  { type:'fill', q:'The committee agreed ___ a compromise after six hours.', a:'on' },
  { type:'fill', q:'She is intent ___ restructuring the entire department.', a:'on' },
  { type:'fill', q:'He is renowned ___ his uncompromising stance on corruption.', a:'for' },
  { type:'fill', q:'The new director is accountable ___ the board of trustees.', a:'to' },
  { type:'fill', q:'The report drew attention ___ several systemic failures.', a:'to' },
  { type:'fill', q:'The CEO resigned in the wake ___ the accounting scandal.', a:'of' },
  { type:'fill', q:'The proposal fell short ___ the required standards.', a:'of' },
  { type:'fill', q:'She takes great pride ___ her ability to remain impartial.', a:'in' },
  { type:'fill', q:'The decision was fraught ___ unintended consequences.', a:'with', hint:'"Fraught with" = full of something negative.' },
  { type:'fill', q:'The verdict was subject ___ appeal.', a:'to' },
  { type:'fill', q:'The salary is commensurate ___ experience and qualifications.', a:'with' },
  { type:'fill', q:'It is incumbent ___ the government to act without delay.', a:'on' },
  { type:'fill', q:'Growth was achieved at the expense ___ workers\' rights.', a:'of' },
  { type:'fill', q:'He received shares in lieu ___ a cash bonus.', a:'of' },
  { type:'fill', q:'The treaty was signed ___ good faith by all parties.', a:'in' },
  { type:'fill', q:'The report was published ___ the auspices of the United Nations.', a:'under' },
  { type:'fill', q:'His statements are at variance ___ his known private views.', a:'with' },
  { type:'fill', q:'Resources must be distributed in proportion ___ need.', a:'to' },
  { type:'fill', q:'The findings must be understood in the context ___ the global recession.', a:'of' },
  { type:'fill', q:'Profits were maximised to the detriment ___ quality.', a:'of' },
  { type:'fill', q:'The law applies equally, irrespective ___ wealth or status.', a:'of' },
  { type:'fill', q:'The company is ___ breach of its contractual obligations.', a:'in' },
  { type:'fill', q:'She acted ___ good faith but was nonetheless held liable.', a:'in' },
  { type:'fill', q:'The investigation was launched at the behest ___ the prime minister.', a:'of' },
  { type:'fill', q:'By virtue ___ her seniority, she holds significant influence.', a:'of' },
  { type:'fill', q:'The drug is most effective ___ conjunction with physiotherapy.', a:'in' },
  { type:'fill', q:'Talks were opened with a view ___ a negotiated settlement.', a:'to' },
  { type:'fill', q:'He is predisposed ___ anxiety due to his upbringing.', a:'to' },
  { type:'fill', q:'The application was rejected ___ the grounds that it was incomplete.', a:'on' },
  { type:'fill', q:'The cut was presented ___ the guise of reform.', a:'in' },
  { type:'fill', q:'She spoke ___ length about the challenges facing the sector.', a:'at' },
  { type:'fill', q:'The decision was taken ___ the knowledge of the full board.', a:'with' },
  { type:'fill', q:'The penalty is disproportionate ___ the severity of the offence.', a:'to' },
  { type:'fill', q:'The measure was taken ___ the interests of national security.', a:'in' },
  { type:'fill', q:'He continued ___ the face of overwhelming opposition.', a:'in' },
  { type:'fill', q:'___ all intents and purposes, the matter has been settled.', a:'For' },
  { type:'fill', q:'The meeting will proceed ___ the absence of the chairman.', a:'in' },
  { type:'fill', q:'The policy was adopted ___ the recommendation of the committee.', a:'on' },
  { type:'fill', q:'She is well-versed ___ the intricacies of international law.', a:'in' },
  { type:'fill', q:'He was oblivious ___ the tension building in the room.', a:'to' },
  { type:'fill', q:'The findings are consistent ___ earlier research on the topic.', a:'with' },
  // Adj + preposition
  { type:'mc', q:'The committee was tasked ___ reviewing the entire regulatory framework.', options:['with','for','by','to'], a:'with' },
  { type:'mc', q:'Her promotion was contingent ___ the successful completion of the project.', options:['on','upon','of','to'], a:'on' },
  { type:'mc', q:'There was no precedent ___ such a drastic measure.', options:['for','of','in','to'], a:'for' },
  { type:'mc', q:'The results were in keeping ___ the company\'s projections.', options:['with','to','by','from'], a:'with' },
  { type:'mc', q:'She is susceptible ___ flattery, which makes her easy to manipulate.', options:['to','of','by','for'], a:'to' },
  { type:'mc', q:'The minister was complicit ___ covering up the scandal.', options:['in','with','to','of'], a:'in' },
  { type:'mc', q:'His career trajectory stands ___ stark contrast to his humble beginnings.', options:['in','at','with','on'], a:'in' },
  { type:'mc', q:'The law is designed to clamp down ___ financial misconduct.', options:['on','at','over','upon'], a:'on' },
  { type:'mc', q:'He is well-versed ___ the intricacies of international tax law.', options:['in','with','on','at'], a:'in' },
  { type:'mc', q:'The measure was taken ___ the grounds of national security.', options:['on','in','by','for'], a:'on' },
  { type:'mc', q:'The policy was implemented ___ conjunction with local authorities.', options:['in','by','on','with'], a:'in' },
  { type:'mc', q:'The talks were conducted ___ the auspices of the UN.', options:['under','in','by','at'], a:'under' },
  { type:'mc', q:'The law applies equally, irrespective ___ wealth or status.', options:['of','to','from','for'], a:'of' },
  { type:'mc', q:'"___ the evidence available, it would be premature to draw conclusions."', options:['Given','Because of','Due to','Since'], a:'Given' },
  { type:'mc', q:'The decision was taken ___ the advice of the legal team.', options:['against','despite','contrary to','in spite'], a:'against' },
  { type:'mc', q:'She is known ___ her uncompromising approach to negotiations.', options:['for','by','of','as'], a:'for' },
  { type:'mc', q:'The contract is subject ___ final board approval.', options:['to','for','by','of'], a:'to' },
  { type:'mc', q:'The agency is ___ no illusions about the difficulty of the task.', options:['under','with','in','at'], a:'under' },
  { type:'mc', q:'He acted ___ good faith, which mitigated his liability.', options:['in','with','by','on'], a:'in' },
  { type:'mc', q:'The court found the defendant guilty ___ fraud.', options:['of','for','with','in'], a:'of' },
  { type:'mc', q:'The board was unanimous ___ its opposition to the merger.', options:['in','on','about','with'], a:'in' },
  { type:'mc', q:'She was reticent ___ discussing the details of the settlement.', options:['about','in','for','to'], a:'about' },
  { type:'mc', q:'The firm is ___ breach of contract and faces significant damages.', options:['in','on','at','by'], a:'in' },
  { type:'mc', q:'The proposal was rejected ___ the grounds that it was unworkable.', options:['on','in','by','for'], a:'on' },
  { type:'mc', q:'She remains committed ___ the principles she has always defended.', options:['to','in','on','for'], a:'to' },
  { type:'mc', q:'He was acquitted ___ all charges after a lengthy trial.', options:['of','from','for','on'], a:'of' },
  { type:'mc', q:'The regulation is ___ keeping with international standards.', options:['in','at','on','by'], a:'in' },
  { type:'mc', q:'The government acted ___ the recommendation of the inquiry.', options:['on','in','by','for'], a:'on' },
  { type:'mc', q:'The treaty is tantamount ___ a formal declaration of war.', options:['to','as','of','for'], a:'to' },
  { type:'mc', q:'She was charged ___ overseeing the entire restructuring process.', options:['with','for','of','by'], a:'with' },
  { type:'mc', q:'The matter is contingent ___ the outcome of the appeal.', options:['on','upon','about','both a and b'], a:'both a and b' },
  { type:'mc', q:'Results were somewhat ___ odds with what the model had predicted.', options:['at','in','on','by'], a:'at' },
  { type:'mc', q:'He is immune ___ prosecution under the current legislation.', options:['from','to','of','against'], a:'from' },
  { type:'mc', q:'The policy runs counter ___ everything the party has stood for.', options:['to','of','with','against'], a:'to' },
  { type:'mc', q:'The organisation is committed ___ environmental sustainability.', options:['to','in','on','for'], a:'to' },
  { type:'mc', q:'She was instrumental ___ securing the funding for the project.', options:['in','on','for','to'], a:'in' },
  { type:'mc', q:'The ruling is binding ___ all member states without exception.', options:['on','for','to','upon'], a:'on' },
],

};
