const DB_REGISTER = {
register: [
  { type:'mc', q:'Which is the most formal way to say "We need to talk about the budget"?', options:['The budget warrants our urgent attention.','We gotta discuss the budget.','The budget needs talking about.','Let\'s chat about the budget.'], a:'The budget warrants our urgent attention.' },
  { type:'mc', q:'Which option best replaces "get worse" in a formal report?', options:['deteriorate','go downhill','get bad','worsen up'], a:'deteriorate' },
  { type:'mc', q:'Replace "find out" with a formal verb: "Investigators will ___ the cause."', options:['ascertain','figure out','work out','dig up'], a:'ascertain' },
  { type:'mc', q:'Most formally replaces "use" in: "We should ___ all available resources."', options:['utilise','make use of','use up','employ'], a:'utilise' },
  { type:'mc', q:'"The new law will start next month." Most formal replacement:', options:['come into effect','kick in','start up','get going'], a:'come into effect' },
  { type:'mc', q:'Formal equivalent of "get rid of the old system":', options:['abolish','throw away','ditch','scrap'], a:'abolish' },
  { type:'mc', q:'Formal equivalent of "look into the allegations":', options:['investigate','check out','look at','probe into'], a:'investigate' },
  { type:'mc', q:'Formal equivalent of "go up": "Costs have ___ significantly this quarter."', options:['escalated','gone up','shot up','jumped'], a:'escalated' },
  { type:'mc', q:'Formal replacement for "put off": "The meeting has been ___."', options:['postponed','put off','delayed back','rescheduled back'], a:'postponed' },
  { type:'mc', q:'Most formal way to say "agree with": "The data ___ the hypothesis."', options:['corroborates','backs up','goes with','fits'], a:'corroborates' },
  { type:'mc', q:'Formal equivalent of "help": "The new software will ___ faster processing."', options:['facilitate','help with','assist in','enable for'], a:'facilitate' },
  { type:'mc', q:'Formal equivalent of "start": "The government ___ a formal review."', options:['initiated','started up','began','kicked off'], a:'initiated' },
  { type:'mc', q:'Formal equivalent of "end": "The contract was ___ with immediate effect."', options:['terminated','ended','stopped','finished'], a:'terminated' },
  { type:'mc', q:'Formal equivalent of "get": "Funding was ___ from a private source."', options:['obtained','got','received','found'], a:'obtained' },
  { type:'mc', q:'Formal equivalent of "check": "All data was independently ___."', options:['verified','checked','looked at','gone over'], a:'verified' },
  { type:'mc', q:'Formal equivalent of "need" in: "The situation ___ urgent attention."', options:['requires','needs','calls for','both a and c'], a:'both a and c' },
  { type:'mc', q:'Formal equivalent of "show": "The data ___ a clear causal link."', options:['demonstrate','show','prove','indicate'], a:'demonstrate' },
  { type:'mc', q:'Formal equivalent of "think": "The board is ___ its options."', options:['considering','thinking about','mulling over','looking at'], a:'considering' },
  { type:'mc', q:'Formal equivalent of "talk about": "The report fails to ___ the root causes."', options:['address','talk about','mention','deal with'], a:'address' },
  { type:'mc', q:'Formal equivalent of "result in": "The strike ___ in the board\'s resignation."', options:['culminated','resulted','ended','led'], a:'culminated' },
  { type:'fill', q:'Her recommendation was ___ by the board, who felt it was impractical. (turn down)', a:'rejected' },
  { type:'fill', q:'The minister ___ that further cuts were unavoidable. (say, admitting reluctantly)', a:'acknowledged' },
  { type:'fill', q:'The grant will ___ the charity to expand its services. (let/allow)', a:'enable' },
  { type:'fill', q:'The committee will ___ a thorough review. (do/carry out)', a:'undertake' },
  { type:'fill', q:'This case ___ the wider problem of regulatory capture. (shows/exemplifies)', a:'illustrates' },
  { type:'fill', q:'The scale of the problem ___ a systemic response. (makes necessary)', a:'necessitates' },
  { type:'fill', q:'Please keep me ___ of any significant developments. (keep informed — formal)', a:'apprised' },
  { type:'fill', q:'The strike ___ in the resignation of the entire board. (resulted in — formal)', a:'culminated' },
  { type:'fill', q:'All documents ___ to the case must be disclosed. (related to — formal/legal)', a:'pertaining' },
  { type:'fill', q:'The commission will ___ an independent investigation into the allegations. (conduct)', a:'conduct' },
],

};
