const DB_TRANSFORMATION = {
transformation: [
  { type:'transform', original:'It is essential that she submits the report on time.', keyword:'IMPERATIVE', clue:'Rewrite using "imperative" in a formal structure.', answer:'It is imperative that she submit(s) the report on time.' },
  { type:'transform', original:'They believe the CEO deliberately misled shareholders.', keyword:'ALLEGED', clue:'Make the claim tentative using a passive construction.', answer:'The CEO is alleged to have deliberately misled shareholders.' },
  { type:'transform', original:'He did not feel any regret about leaving the company.', keyword:'COMPUNCTION', clue:'Use the noun "compunction" (= hesitation, guilt).', answer:'He felt no compunction about leaving the company.' },
  { type:'transform', original:'Nobody could have predicted the scale of the disaster.', keyword:'FORESEEN', clue:'Passive with modal perfect.', answer:'The scale of the disaster could not have been foreseen.' },
  { type:'transform', original:'She is too proud to admit that she was wrong.', keyword:'PRIDE', clue:'Use "her pride prevents her from..."', answer:'Her pride prevents her from admitting she was wrong.' },
  { type:'transform', original:'The reforms were less effective than the government had hoped.', keyword:'FELL', clue:'"Fall short of" — the reforms fell short of expectations.', answer:'The reforms fell short of the government\'s hopes/expectations.' },
  { type:'transform', original:'He only agreed because he was under enormous pressure.', keyword:'DURESS', clue:'"Under duress" = under pressure/coercion.', answer:'He only agreed under duress.' },
  { type:'transform', original:'Many people think that the minister acted unethically.', keyword:'WIDELY', clue:'Passive + adverb: "is widely believed/considered..."', answer:'The minister is widely believed/considered to have acted unethically.' },
  { type:'transform', original:'The project was cancelled because it would have cost too much.', keyword:'PROHIBITIVE', clue:'"Prohibitive cost" = too expensive.', answer:'The project was cancelled due to the prohibitive cost.' },
  { type:'transform', original:'The two proposals cannot both be accepted.', keyword:'MUTUALLY', clue:'"Mutually exclusive" = cannot coexist.', answer:'The two proposals are mutually exclusive.' },
  { type:'transform', original:'It is very unlikely that prices will fall this year.', keyword:'REMOTE', clue:'"Remote possibility/chance" = very unlikely.', answer:'There is a remote possibility that prices will fall this year.' },
  { type:'transform', original:'The minister refused to explain the delay.', keyword:'ACCOUNT', clue:'"Account for" = explain.', answer:'The minister refused to account for the delay.' },
  { type:'transform', original:'If the government had acted sooner, the crisis might have been averted.', keyword:'HAD', clue:'Inversion in third conditional.', answer:'Had the government acted sooner, the crisis might have been averted.' },
  { type:'transform', original:'Despite working very hard, she failed to win the contract.', keyword:'EFFORTS', clue:'"Despite her efforts..."', answer:'Despite her efforts, she failed to win the contract.' },
  { type:'transform', original:'She has been in charge of the crisis management for three weeks.', keyword:'HELM', clue:'"At the helm of" = in charge of.', answer:'She has been at the helm of the crisis management for three weeks.' },
  { type:'transform', original:'The two countries\' interests are fundamentally different.', keyword:'DIVERGE', clue:'"Interests diverge sharply."', answer:'The two countries\' interests diverge significantly/sharply.' },
  { type:'transform', original:'The government took the decision without consulting experts.', keyword:'WITHOUT', clue:'Passive: "The decision was taken without..."', answer:'The decision was taken without consulting experts / without expert consultation.' },
  { type:'transform', original:'He was the only employee who dared to challenge the board.', keyword:'ALONE', clue:'"He alone dared..." or "He was alone in daring..."', answer:'He alone dared to challenge the board.' },
  { type:'transform', original:'Nobody doubts that the economy is in serious difficulty.', keyword:'QUESTION', clue:'"There is no question that..."', answer:'There is no question that the economy is in serious difficulty.' },
  { type:'transform', original:'It would appear that the system was deliberately compromised.', keyword:'DELIBERATE', clue:'"The system appears to have been deliberately compromised."', answer:'The system appears to have been deliberately compromised.' },
  { type:'transform', original:'She worked extremely hard but still did not pass the exam.', keyword:'HARD', clue:'"Try as she might / Hard as she tried..."', answer:'Hard as she tried, she still did not pass the exam. / Try as she might, she still did not pass.' },
  { type:'transform', original:'The company no longer produces this model.', keyword:'DISCONTINUED', clue:'Passive: "This model has been discontinued."', answer:'This model has been discontinued by the company.' },
  { type:'transform', original:'It is very important that all staff are informed of the changes.', keyword:'PARAMOUNT', clue:'"It is of paramount importance that..."', answer:'It is of paramount importance that all staff are informed of the changes.' },
  { type:'transform', original:'The new law makes it illegal to discriminate on grounds of age.', keyword:'UNLAWFUL', clue:'Rephrase: "The new law renders / makes age discrimination unlawful."', answer:'The new law renders age discrimination unlawful. / Age discrimination is made unlawful by the new law.' },
],

};
