const DB_WORDFORMATION = {
wordformation: [
  { type:'fill', q:'Despite the setbacks, she remained utterly undeterred. (DETER)', a:'undeterred' },
  { type:'fill', q:'The scientist\'s findings were met with deep ___. (SCEPTIC)', a:'scepticism' },
  { type:'fill', q:'The merger created an ___ powerful conglomerate. (PRECEDENT)', a:'unprecedented' },
  { type:'fill', q:'The new regulations will impose significant ___ on businesses. (CONSTRAIN)', a:'constraints' },
  { type:'fill', q:'Her ___ to compromise made negotiations difficult. (UNWILL)', a:'unwillingness' },
  { type:'fill', q:'The senator\'s remarks were criticised for their ___. (TACT)', a:'tactlessness' },
  { type:'fill', q:'The ___ of the two companies was announced at a press conference. (MERGE)', a:'merger' },
  { type:'fill', q:'There is a certain ___ to the minister\'s position. (INCOHERE)', a:'incoherence' },
  { type:'fill', q:'The claims are utterly ___. (FOUND)', a:'unfounded' },
  { type:'fill', q:'Her ___ of the situation proved to be entirely accurate. (ASSESS)', a:'assessment' },
  { type:'fill', q:'The project\'s ___ has been called into question by the audit. (FEASIBLE)', a:'feasibility' },
  { type:'fill', q:'The attorney launched a scathing ___ of the prosecution\'s case. (REBUT)', a:'rebuttal' },
  { type:'fill', q:'The policy was seen as ___ — it solved one problem while creating others. (COUNTER)', a:'counterproductive' },
  { type:'fill', q:'The rise of automation has led to widespread economic ___. (DISPLACE)', a:'displacement' },
  { type:'fill', q:'His ___ handling of the crisis drew widespread criticism. (INEPT)', a:'ineptitude' },
  { type:'fill', q:'The proposal is ___ flawed at a fundamental level. (FUND)', a:'fundamentally' },
  { type:'fill', q:'The verdict was ___ disproportionate to the severity of the offence. (WHOLE)', a:'wholly' },
  { type:'fill', q:'She is ___ the most qualified candidate for the position. (DISPUTE)', a:'indisputably' },
  { type:'fill', q:'It is ___ that nobody was aware of the problem at the time. (CONCEIVE)', a:'inconceivable' },
  { type:'fill', q:'The committee expressed grave ___ about the proposed changes. (RESERVE)', a:'reservations' },
  { type:'fill', q:'The ___ of the evidence cannot be ignored. (ACCUMULATE)', a:'accumulation' },
  { type:'fill', q:'The measure was deemed ___ in the circumstances. (JUSTIFY)', a:'justifiable' },
  { type:'fill', q:'The investigation revealed a pattern of ___ misconduct. (SYSTEM)', a:'systematic' },
  { type:'fill', q:'The findings were regarded as highly ___ by the scientific community. (SIGNIFY)', a:'significant' },
  { type:'fill', q:'The ruling has ___ consequences for the entire sector. (IMPLY)', a:'implications' },
  { type:'fill', q:'She spoke with great ___ about the challenges that lay ahead. (CANDID)', a:'candour' },
  { type:'fill', q:'The government showed a remarkable ___ to engage with the evidence. (WILLING)', a:'unwillingness', hint:'un- + willing + -ness.' },
  { type:'fill', q:'The proposal was criticised for its ___ and lack of detail. (VAGUE)', a:'vagueness' },
  { type:'fill', q:'His ___ approach to risk management was noted as exceptional. (PRAGMATIC)', a:'pragmatic', hint:'Already an adjective — confirm the correct form in context.' },
  { type:'fill', q:'The ___ of the claim was immediately questioned by experts. (PLAUSIBLE)', a:'plausibility' },
  { type:'mc', q:'The committee expressed grave ___ about the proposed changes. (RESERVE)', options:['reservations','reserves','reservedness','reserving'], a:'reservations' },
  { type:'mc', q:'His ___ of the situation proved to be entirely accurate. (ASSESS)', options:['assessment','assessing','assessibility','assessor'], a:'assessment' },
  { type:'mc', q:'The project\'s ___ has been called into question. (FEASIBLE)', options:['feasibility','feasibleness','feasibly','feasiblility'], a:'feasibility' },
  { type:'mc', q:'The policy was seen as ___. (COUNTER)', options:['counterproductive','counterable','counteracted','counterfeit'], a:'counterproductive' },
  { type:'mc', q:'The rise of automation has led to widespread economic ___. (DISPLACE)', options:['displacement','displacing','displacedness','displacings'], a:'displacement' },
  { type:'mc', q:'___ constraints mean the project cannot expand. (FINANCE)', options:['Financial','Financially','Financed','Finance'], a:'Financial' },
  { type:'mc', q:'The measures were deemed ___ to the threat. (PROPORTION)', options:['disproportionate','unproportionate','misproportion','disproportional'], a:'disproportionate' },
  { type:'mc', q:'Her ___ to engage with the issue surprised many observers. (REFUSE)', options:['refusal','refusing','refused','refusement'], a:'refusal' },
  { type:'mc', q:'The ___ of the evidence cannot be ignored. (ACCUMULATE)', options:['accumulation','accumulateness','accumulative','accumulacy'], a:'accumulation' },
  { type:'mc', q:'The findings were regarded as highly ___ by scientists. (SIGNIFY)', options:['significant','signifying','significance','significative'], a:'significant' },
],

};
