const THEORY_CONFUSABLES = {
confusables: {
  title: 'Confusables',
  intro: 'Words frequently confused at C1/C2 level — because they look similar, are false friends, or are commonly misused even by advanced speakers. These are classic exam pitfalls.',
  entries: [
    { term:'affect (verb) vs effect (noun)', pos:'classic pair', meaning:'"Affect" = to have an impact on (verb). "Effect" = a result (noun).', examples:['The drought has severely <em>affected</em> crop yields.','The <em>effect</em> of the drought has been severe.'], note:'"Effect" can also be a verb = "to bring about": "to <em>effect</em> change" — rare but tested at C2.' },
    { term:'fewer vs less', pos:'determiner pair', meaning:'"Fewer" with countable nouns. "Less" with uncountable nouns.', examples:['<em>Fewer</em> participants attended than expected.','There was <em>less</em> enthusiasm than anticipated.'] },
    { term:'imply vs infer', pos:'verb pair', meaning:'"Imply" = to suggest (speaker/writer). "Infer" = to deduce (reader/listener).', examples:['The data <em>imply</em> a causal relationship.','From the data, we can <em>infer</em> a causal relationship.'], note:'Error: "The report *infers* that..." should be "The report *implies* that..."' },
    { term:'economic vs economical', pos:'adjective pair', meaning:'"Economic" = relating to the economy. "Economical" = cost-effective; not wasteful.', examples:['The country faces serious <em>economic</em> challenges.','An <em>economical</em> use of resources is essential.'] },
    { term:'comprehensive vs comprehensible', pos:'adjective pair', meaning:'"Comprehensive" = thorough; covering all aspects. "Comprehensible" = understandable.', examples:['She produced a <em>comprehensive</em> report.','The explanation was barely <em>comprehensible</em> to a non-specialist.'] },
    { term:'further vs farther', pos:'adverb pair', meaning:'"Further" = additional; more (abstract). "Farther" = greater physical distance.', examples:['We need to go <em>further</em> in our analysis.','The second site is <em>farther</em> from the city centre.'] },
    { term:'daunted vs daunting', pos:'-ed / -ing adjective pair', meaning:'"-ed" = how a person feels. "-ing" = property of the thing causing the feeling.', examples:['She felt <em>daunted</em> by the complexity.','The complexity of the task was <em>daunting</em>.'], note:'Applies to all such pairs: overwhelmed/overwhelming, frustrated/frustrating.' },
    { term:'accept vs agree', pos:'verb pair', meaning:'"Accept" + noun (offer, responsibility, proposal). "Agree to do" or "agree on" a point.', examples:['She <em>accepted</em> full responsibility.','The board <em>agreed to</em> delay the vote.'], note:'"Accept to do" is a very common non-native error.' },
    { term:'despite vs although', pos:'conjunction pair', meaning:'"Despite" + noun/gerund. "Although" + clause.', examples:['<em>Despite</em> the setbacks, progress was made.','<em>Although</em> there were setbacks, progress was made.'], note:'"Despite of" is ALWAYS wrong.' },
    { term:'sensible vs sensitive', pos:'adjective pair', meaning:'"Sensible" = showing good judgement. "Sensitive" = responsive to feelings; easily affected.', examples:['A <em>sensible</em> approach is essential.','The issue is politically <em>sensitive</em>.'] },
    { term:'principal vs principle', pos:'homophone pair', meaning:'"Principal" = main (adj) or head of institution (noun). "Principle" = fundamental rule or belief.', examples:['The <em>principal</em> cause was poor communication.','She refused to compromise on her <em>principles</em>.'] },
    { term:'disinterested vs uninterested', pos:'adjective pair', meaning:'"Disinterested" = impartial; no personal stake. "Uninterested" = not interested.', examples:['We need a <em>disinterested</em> party to arbitrate.','She seemed completely <em>uninterested</em> in the outcome.'], note:'One of the most commonly confused pairs at C2. "Disinterested" ≠ "not interested".' },
    { term:'comprise vs consist of', pos:'verb pair', meaning:'"Comprise" = be made up of (no "of" after it). "Consist of" = be made up of.', examples:['The committee <em>comprises</em> seven members.','The committee <em>consists of</em> seven members.'], note:'"Comprised of" is widely used but traditionally incorrect in formal writing.' },
    { term:'alternate vs alternative', pos:'adjective pair', meaning:'"Alternate" = every other one in a sequence. "Alternative" = another option.', examples:['The committee meets on <em>alternate</em> Tuesdays.','We need to find an <em>alternative</em> solution.'], note:'In AmE, "alternate" is also used to mean "alternative".' },
    { term:'credible vs credulous vs creditable', pos:'adjective trio', meaning:'"Credible" = believable. "Credulous" = too willing to believe; gullible. "Creditable" = deserving praise.', examples:['The witness gave a <em>credible</em> account.','He was <em>credulous</em> enough to fall for the scheme.','She gave a <em>creditable</em> performance under difficult circumstances.'] },
    { term:'appraise vs apprise', pos:'verb pair', meaning:'"Appraise" = to assess value or quality. "Apprise" = to inform someone (formal).', examples:['The property was <em>appraised</em> at £500,000.','Please keep me <em>apprised</em> of any developments.'] },
    { term:'mitigate vs militate', pos:'verb pair', meaning:'"Mitigate" = to reduce severity. "Militate (against)" = to be a factor working against.', examples:['Steps were taken to <em>mitigate</em> the environmental impact.','These factors <em>militate against</em> a quick recovery.'] },
    { term:'reticent vs reluctant', pos:'adjective pair', meaning:'"Reticent" = unwilling to speak openly. "Reluctant" = unwilling to do something.', examples:['He was characteristically <em>reticent</em> about his personal life.','She was <em>reluctant</em> to commit to a specific timeline.'], note:'"Reticent" strictly refers to unwillingness to speak or disclose — not reluctance to act.' },
    { term:'enormity vs enormousness', pos:'noun pair', meaning:'"Enormity" = the extreme scale of something shocking or morally severe. "Enormousness" = sheer size.', examples:['The <em>enormity</em> of the crime slowly became apparent.','The <em>enormousness</em> of the building was immediately striking.'], note:'Using "enormity" to mean simply "very large" is considered an error in formal writing.' },
    { term:'unexceptional vs unexceptionable', pos:'adjective pair', meaning:'"Unexceptional" = ordinary; nothing special. "Unexceptionable" = not open to objection; perfectly acceptable.', examples:['His performance was <em>unexceptional</em> — adequate but unremarkable.','The terms of the contract are entirely <em>unexceptionable</em>.'] },
    { term:'continuous vs continual', pos:'adjective pair', meaning:'"Continuous" = without interruption; unbroken. "Continual" = frequently repeated, but with breaks.', examples:['The machine runs on a <em>continuous</em> loop.','There were <em>continual</em> interruptions throughout the meeting.'] },
    { term:'historic vs historical', pos:'adjective pair', meaning:'"Historic" = important in history; likely to be remembered. "Historical" = relating to history or the past.', examples:['This is a <em>historic</em> moment for the nation.','The researchers examined <em>historical</em> records dating back to 1800.'] },
    { term:'practicable vs practical', pos:'adjective pair', meaning:'"Practicable" = able to be done; feasible. "Practical" = sensible; good at getting things done.', examples:['No <em>practicable</em> alternative was identified.','She is an extremely <em>practical</em> person who gets results.'] },
    { term:'prescribe vs proscribe', pos:'verb pair', meaning:'"Prescribe" = to recommend or officially order. "Proscribe" = to officially forbid.', examples:['The protocol <em>prescribes</em> a specific course of action.','The treaty <em>proscribes</em> the use of chemical weapons.'] },
    { term:'refute vs rebut vs deny', pos:'verb trio', meaning:'"Refute" = to disprove conclusively. "Rebut" = to argue against. "Deny" = to say it is not true.', examples:['She <em>refuted</em> the allegations with documentary evidence. (proved them wrong)', 'He <em>rebutted</em> each claim in turn. (argued against)', 'The minister simply <em>denied</em> any wrongdoing. (stated it wasn\'t true)'], note:'Using "refute" to mean merely "deny" is a common error in journalism and informal writing.' },
    { term:'infer vs imply (revisited for writing)', pos:'note', meaning:'Reinforcement: The text/speaker <em>implies</em>; the reader/listener <em>infers</em>.', examples:['The author <em>implies</em> that the government was complicit.','Readers naturally <em>infer</em> that the character is lying.'] },
  ]
},


};
