const THEORY_REGISTER = {
register: {
  title: 'Formal Register',
  intro: 'Formal register requires replacing colloquial or imprecise language with accurate, elevated vocabulary. Essential for C1/C2 writing tasks, academic essays, and professional communication.',
  entries: [
    { term:'find out → ascertain', pos:'verb (informal → formal)', meaning:'To discover or establish something with certainty.', examples:['Investigators sought to <em>ascertain</em> whether the regulations had been breached.'] },
    { term:'use → utilise / employ', pos:'verb (informal → formal)', meaning:'"Utilise" = make effective use of. "Employ" = use in a systematic way.', examples:['The model <em>utilises</em> machine learning.','A novel methodology was <em>employed</em> in the study.'] },
    { term:'get worse → deteriorate', pos:'verb (informal → formal)', meaning:'To become progressively worse.', examples:['Relations between the two nations have <em>deteriorated</em> markedly.'] },
    { term:'start / come into effect', pos:'verb phrase', meaning:'(Of a law or policy) to begin operating officially.', examples:['The legislation will <em>come into effect</em> on 1 January.'] },
    { term:'say → acknowledge / assert / concede / contend / maintain', pos:'reporting verbs', meaning:'Each carries a specific attitude: acknowledge (admit), assert (claim), concede (yield), contend (argue), maintain (continue to claim despite opposition).', examples:['The minister <em>acknowledged</em> that further cuts were unavoidable.','The report <em>asserts</em> that risks were understated.','She <em>maintains</em> her innocence.','Counsel <em>contends</em> that the contract was never valid.'] },
    { term:'agree with → corroborate / substantiate', pos:'verb (informal → formal)', meaning:'"Corroborate" = confirm with evidence. "Substantiate" = prove with evidence.', examples:['The forensic evidence <em>corroborates</em> the witness\'s account.','The claimant failed to <em>substantiate</em> the allegations.'] },
    { term:'get rid of → abolish / eradicate / eliminate', pos:'verb (informal → formal)', meaning:'"Abolish" = formally end. "Eradicate" = destroy completely. "Eliminate" = remove.', examples:['The government pledged to <em>abolish</em> the tax.','The aim is to <em>eradicate</em> extreme poverty by 2030.'] },
    { term:'go up → escalate / surge / rise sharply', pos:'verb phrase', meaning:'"Escalate" = increase progressively. "Surge" = increase suddenly.', examples:['Costs have <em>escalated</em> well beyond projections.','Unemployment <em>surged</em> following the closures.'] },
    { term:'put off → postpone / defer', pos:'verb (informal → formal)', meaning:'"Postpone" = rearrange for later. "Defer" = delay pending conditions.', examples:['The hearing has been <em>postponed</em> pending evidence.','A final decision was <em>deferred</em> until the next session.'] },
    { term:'warrant (formal "needs")', pos:'verb (formal)', meaning:'"Warrant" = to justify, merit, or make necessary.', examples:['The matter <em>warrants</em> further investigation.','Such allegations <em>warrant</em> an immediate response.'] },
    { term:'turn down → reject / decline / dismiss', pos:'verb (informal → formal)', meaning:'"Decline" (polite), "reject" (firm), "dismiss" (contemptuous).', examples:['The application was <em>rejected</em> on procedural grounds.','She <em>declined</em> to comment.','The judge <em>dismissed</em> the appeal as wholly without merit.'] },
    { term:'look into → investigate / examine / probe', pos:'verb (informal → formal)', meaning:'"Investigate" = formal inquiry. "Examine" = careful analysis. "Probe" = searching inquiry.', examples:['A committee was established to <em>investigate</em> the allegations.','Auditors were called in to <em>examine</em> the accounts.'] },
    { term:'show → demonstrate / illustrate / indicate / reveal', pos:'verb group', meaning:'Precise alternatives: demonstrate (prove), illustrate (exemplify), indicate (suggest), reveal (uncover).', examples:['The data <em>demonstrate</em> a clear causal link.','This case <em>illustrates</em> the wider problem.','Early results <em>indicate</em> a shift.','The audit <em>revealed</em> irregularities.'] },
    { term:'help → facilitate / enable / assist', pos:'verb (informal → formal)', meaning:'"Facilitate" = make possible. "Enable" = give means. "Assist" = provide support.', examples:['The software will <em>facilitate</em> faster processing.','The grant will <em>enable</em> the charity to expand.'] },
    { term:'important → significant / pivotal / critical / crucial / paramount', pos:'adj group', meaning:'Degrees: significant (notable), crucial/critical (essential), pivotal (turning point), paramount (supreme).', examples:['This is a <em>pivotal</em> moment.','Access to clean water is <em>critical</em> for public health.','Security is of <em>paramount</em> importance.'] },
    { term:'but → however / nevertheless / nonetheless / yet / that said', pos:'conj group', meaning:'Formal adversative connectors. "Nevertheless/nonetheless" signal stronger concessions.', examples:['The evidence is compelling. <em>Nevertheless</em>, further testing is required.','The challenge is significant; <em>however</em>, it is not insurmountable.'] },
    { term:'do → undertake / conduct / carry out / perform', pos:'verb group', meaning:'Formal alternatives for "do" with specific nouns.', examples:['The committee will <em>undertake</em> a thorough review.','A study was <em>conducted</em> by an independent body.','Tests were <em>carried out</em> over a six-month period.','The surgeon <em>performed</em> the procedure.'] },
    { term:'need → require / necessitate / call for', pos:'verb (informal → formal)', meaning:'"Require" = need formally. "Necessitate" = make necessary. "Call for" = demand.', examples:['The situation <em>requires</em> urgent attention.','The scale of the problem <em>necessitates</em> a systemic response.','The findings <em>call for</em> immediate action.'] },
    { term:'start → initiate / commence / launch / instigate', pos:'verb group', meaning:'Formal synonyms for "start", each with nuances of agency and formality.', examples:['The government <em>initiated</em> a formal review.','Proceedings have <em>commenced</em>.','An inquiry was <em>launched</em>.','He was accused of <em>instigating</em> the unrest.'] },
    { term:'end → conclude / terminate / cease / discontinue', pos:'verb group', meaning:'"Conclude" = come to an end naturally. "Terminate" = bring to an end formally. "Cease" = stop. "Discontinue" = stop a practice.', examples:['The trial has <em>concluded</em>.','The contract was <em>terminated</em> with immediate effect.','Production has <em>ceased</em>.','The drug was <em>discontinued</em> due to side effects.'] },
    { term:'think → consider / deliberate / contemplate / envisage', pos:'verb group', meaning:'Different degrees and types of mental activity: consider (weigh up), deliberate (discuss carefully), contemplate (think deeply), envisage (imagine a future scenario).', examples:['The board is <em>considering</em> its options.','The committee <em>deliberated</em> for two days.','The report <em>envisages</em> a 20% reduction in emissions.'] },
    { term:'get → obtain / acquire / procure / secure', pos:'verb (informal → formal)', meaning:'"Obtain" = acquire through effort. "Procure" = formal/legal. "Secure" = obtain with effort/competition.', examples:['Funding was <em>obtained</em> from a private source.','Materials must be <em>procured</em> through an approved supplier.','She <em>secured</em> a majority on the committee.'] },
    { term:'check → verify / scrutinise / audit / validate', pos:'verb group', meaning:'"Verify" = confirm accuracy. "Scrutinise" = examine closely. "Audit" = formal official check. "Validate" = confirm officially.', examples:['All data was independently <em>verified</em>.','The accounts were <em>audited</em> externally.','The methodology was <em>validated</em> by a peer review panel.'] },
    { term:'result in → give rise to / bring about / culminate in / lead to', pos:'verb group', meaning:'Formal alternatives for "result in", varying by type of causation.', examples:['The strike <em>culminated in</em> the resignation of the entire board.','The reforms <em>gave rise to</em> widespread unrest.'] },
    { term:'about → regarding / concerning / with respect to / pertaining to', pos:'prep (informal → formal)', meaning:'"Regarding / concerning" = general formal use. "Pertaining to" = formal/legal.', examples:['Please contact us <em>regarding</em> your application.','All documents <em>pertaining to</em> the case must be disclosed.'] },
  ]
},


};
