const THEORY_GRAMMAR = {
grammar: {
  title: 'Advanced Grammar',
  intro: 'Key grammatical structures that distinguish C1/C2 from lower levels. These cover complex clauses, advanced tenses, and formal syntactic patterns tested in CAE, CPE, and academic writing.',
  entries: [
    { term:'Mixed conditionals', pos:'grammar structure', meaning:'Mixing time frames in conditional sentences.', examples:['<em>If she had taken the job</em> (past hypothetical), <em>she would be living</em> in London now. (present result)', '<em>If he were more disciplined</em> (present state), <em>he would have finished</em> the project by now. (past result)'], note:'The key is identifying whether the condition and result are in the same time frame.' },
    { term:'Subjunctive mood', pos:'grammar structure', meaning:'Used after "it is essential/vital/imperative/recommended/suggested that" and in formal usage.', examples:['It is essential that she <em>submit</em> (not "submits") the report on time.','It was recommended that the committee <em>be dissolved</em>.','I suggest that the motion <em>be tabled</em>.'], note:'The subjunctive uses the base form of the verb for all persons.' },
    { term:'Cleft sentences (It is... that / What...is)', pos:'grammar structure', meaning:'Used to emphasise a particular element of a sentence.', examples:['<em>It was the lack of transparency that</em> caused the crisis. (emphasises cause)', '<em>What concerned us most was</em> the speed of the deterioration.','<em>It is only now that</em> the full extent of the damage is becoming clear.'], note:'"It was X that Y" emphasises X. "What X did was Y" emphasises the action.' },
    { term:'Nominalisation', pos:'grammar structure', meaning:'Converting verbs and adjectives into nouns for a more formal, abstract style.', examples:['She decided to invest → <em>The decision to invest</em>...','They failed to comply → <em>Their failure to comply</em>...'], note:'A hallmark of academic writing. Overuse can make prose unnecessarily dense.' },
    { term:'Complex passive constructions', pos:'grammar structure', meaning:'The passive is used in formal writing to omit agents, create objectivity, or focus on results.', examples:['The data <em>were collected</em> over a three-year period.','It <em>has been suggested that</em> further cuts may be necessary.','The matter <em>is being considered</em> at the highest level.'], note:'Use passive when the agent is unknown, unimportant, or deliberately withheld.' },
    { term:'Relative clauses (advanced)', pos:'grammar structure', meaning:'Non-defining relative clauses with "which" referring to the whole clause; "whose" for things; "whereby" for formal methods.', examples:['The report was delayed, <em>which</em> caused considerable frustration.','A system <em>whereby</em> employees can raise concerns anonymously is essential.','The company, <em>whose</em> headquarters are in Dublin, has announced a restructure.'], note:'"Whereby" = by means of which. Exclusively formal.' },
    { term:'Participle clauses', pos:'grammar structure', meaning:'Reduce relative or adverbial clauses for concision in formal writing.', examples:['<em>Having reviewed</em> all the evidence, the committee reached a verdict. (= After it had reviewed...)', '<em>Faced with</em> mounting pressure, the minister resigned.','The policy, <em>introduced</em> in 2020, has been widely criticised.'], note:'The participle subject must match the main clause subject. Mismatch = dangling participle (error).' },
    { term:'Modal perfects', pos:'grammar structure', meaning:'Modal + have + past participle. Used for deduction, criticism, or speculation about the past.', examples:['He <em>must have known</em> about the irregularities. (deduction)', 'She <em>should have disclosed</em> the conflict of interest. (obligation not met)', 'They <em>could have handled</em> it more sensitively. (unrealised possibility)', 'The decision <em>may have been</em> influenced by external pressure. (speculation)'] },
    { term:'Ellipsis and substitution', pos:'grammar structure', meaning:'Omitting or replacing words understood from context — typical in formal written English.', examples:['Some analysts predicted recovery; others <em>did not (predict recovery)</em>.','The minister was asked to resign, and eventually <em>did so</em>.'], note:'"Do so" is the formal substitute for a repeated verb phrase. "Do it" is more informal.' },
    { term:'Fronting (topicalisation)', pos:'grammar structure', meaning:'Moving an element to the front of the sentence for emphasis or cohesion.', examples:['<em>The economic implications</em>, we have not yet fully understood.','<em>Particularly troubling</em> is the rate at which trust has been eroded.','<em>Of particular note</em> are the three recommendations in section four.'], note:'Common in academic and formal written English. Signals what the writer is focusing on.' },
    { term:'Reporting verbs + structures', pos:'grammar structure', meaning:'Different reporting verbs require different grammatical structures.', examples:['She <em>suggested (that) he should reconsider</em> / <em>suggested reconsidering</em>.','He <em>denied having</em> met the official.','The minister <em>admitted to making</em> an error.','They <em>urged the committee to act</em> immediately.','Critics <em>accused him of misleading</em> Parliament.'], note:'"Suggest" → gerund or that-clause. "Deny/admit" → gerund. "Urge/encourage/persuade" → to-infinitive.' },
    { term:'Concessive clauses', pos:'grammar structure', meaning:'Acknowledging a point while maintaining the main argument.', examples:['<em>However much</em> we may disagree, the decision is final.','<em>Much as</em> I respect her judgement, I cannot support this proposal.','<em>Whatever</em> the outcome, the effort will not have been wasted.','<em>Notwithstanding the fact that</em> the evidence was limited, the verdict was upheld.'] },
    { term:'as/though + inversion (formal concession)', pos:'grammar structure', meaning:'"Adjective/Adverb/Noun + as/though + subject + verb" = concessive structure.', examples:['<em>Difficult as</em> the situation is, there are reasons for optimism.','<em>Much as</em> he tried, he could not convince the committee.','<em>Impressive though</em> the results are, they must be interpreted with caution.'], note:'The adjective or adverb moves to the front. This is a formal and distinctive C2 structure.' },
    { term:'wish / if only + advanced structures', pos:'grammar structure', meaning:'Expressing regret (past), desire for change (present), or complaint (would).', examples:['I <em>wish</em> the government <em>had acted</em> sooner. (past regret)', 'If only the committee <em>were</em> more transparent. (present wish; subjunctive)', 'I wish he <em>would stop</em> evading the question. (complaint about present behaviour)'], note:'"Wish + would" expresses irritation about someone\'s behaviour, not a hypothetical.' },
    { term:'have something done (causative)', pos:'grammar structure', meaning:'To arrange for someone else to do something for you.', examples:['The company <em>had its accounts audited</em> by an independent firm.','She <em>had the contract reviewed</em> before signing.'], note:'Also used passively for unwanted events: "She <em>had her car stolen</em>." (= it happened to her).' },
    { term:'Subjunctive in formal clauses', pos:'grammar structure', meaning:'Used after expressions of demand, recommendation, or necessity in formal style.', examples:['It is imperative that all staff <em>be informed</em>.','The committee recommended that the policy <em>be withdrawn</em>.','The court ordered that he <em>appear</em> in person.'], note:'The subjunctive uses the base form for all persons, including third person singular (no -s).' },
  ]
}


};
