const THEORY_FIXED = {
fixed: {
  title: 'Fixed Phrases & Discourse Markers',
  intro: 'Standard phrases used in formal writing and speech to organise arguments, signal concessions, and express logical relationships. Essential for IELTS Academic, CAE, CPE, and professional writing.',
  entries: [
    { term:'given (that)', pos:'prep / conj', meaning:'Taking into account; considering. More formal than "because of" or "since".', examples:['<em>Given</em> the available evidence, further investigation is essential.','<em>Given that</em> resources are limited, prioritisation is unavoidable.'] },
    { term:'that said', pos:'discourse marker', meaning:'However; in spite of what was just mentioned.', examples:['The plan has several flaws. <em>That said</em>, it represents a significant step forward.'], note:'Near-equivalents: nevertheless, nonetheless, be that as it may, even so.' },
    { term:'notwithstanding', pos:'prep / adverb', meaning:'In spite of; nevertheless (very formal; often legal).', examples:['<em>Notwithstanding</em> these objections, the board voted to proceed.','The risks, <em>notwithstanding</em>, were deemed acceptable.'] },
    { term:'if substantiated', pos:'conditional clause', meaning:'If proved to be true (formal passive structure).', examples:['The allegations, <em>if substantiated</em>, would constitute a serious breach of trust.'] },
    { term:'for all intents and purposes', pos:'fixed phrase', meaning:'In every practical sense; effectively.', examples:['The company has, <em>for all intents and purposes</em>, ceased trading.'] },
    { term:'under no illusions', pos:'fixed phrase', meaning:'Fully and realistically aware of a difficult situation.', examples:['We are <em>under no illusions</em> about the scale of the challenge ahead.'] },
    { term:'wide of the mark', pos:'fixed phrase', meaning:'Inaccurate; significantly missing the point or target.', examples:['His predictions proved <em>wide of the mark</em>.'] },
    { term:'apart from', pos:'prep phrase', meaning:'With the exception of; besides.', examples:['<em>Apart from</em> a few minor inconsistencies, the report is thorough.'] },
    { term:'open to interpretation', pos:'adj phrase', meaning:'Capable of being understood in more than one way; ambiguous.', examples:['The wording of the clause is deliberately <em>open to interpretation</em>.'] },
    { term:'paradigm shift', pos:'noun phrase', meaning:'A fundamental change in underlying assumptions or approach.', examples:['The internet represented a <em>paradigm shift</em> in human communication.'] },
    { term:'with flying colours', pos:'fixed phrase', meaning:'With great success; achieving an excellent result.', examples:['She passed the bar examination <em>with flying colours</em>.'] },
    { term:'against the advice of', pos:'prep phrase', meaning:'Not following the recommendation of.', examples:['The procedure was carried out <em>against the advice of</em> the medical team.'] },
    { term:'by the same token', pos:'discourse marker', meaning:'For the same reason; equally.', examples:['You cannot demand transparency and, <em>by the same token</em>, refuse to disclose your own finances.'] },
    { term:'it stands to reason that', pos:'fixed phrase', meaning:'It is logical or obvious that.', examples:['<em>It stands to reason that</em> increased demand will push prices up.'] },
    { term:'in the final analysis', pos:'discourse marker', meaning:'When everything has been considered; ultimately.', examples:['<em>In the final analysis</em>, the decision rests with the electorate.'] },
    { term:'at one\'s discretion', pos:'prep phrase', meaning:'According to one\'s own judgement.', examples:['The penalty may be waived <em>at the judge\'s discretion</em>.'] },
    { term:'by the same token', pos:'discourse marker', meaning:'Equally; for the same reason.', examples:['Efficiency must be improved. <em>By the same token</em>, quality cannot be sacrificed.'] },
    { term:'cut corners', pos:'fixed phrase', meaning:'To do something to a lower standard to save time or money.', examples:['Safety risks arose because contractors had <em>cut corners</em>.'] },
    { term:'it is worth noting that', pos:'fixed phrase', meaning:'A standard academic marker drawing attention to a detail.', examples:['<em>It is worth noting that</em> the study involved only a small sample.'] },
    { term:'on balance', pos:'discourse marker', meaning:'Taking everything into consideration; overall.', examples:['<em>On balance</em>, the advantages appear to outweigh the risks.'] },
    { term:'suffice it to say', pos:'fixed phrase', meaning:'It is enough to say; I will say only this much.', examples:['<em>Suffice it to say</em>, the outcome was not what anyone had hoped for.'] },
    { term:'in no uncertain terms', pos:'fixed phrase', meaning:'Very clearly and directly; without ambiguity.', examples:['She told him <em>in no uncertain terms</em> that his conduct was unacceptable.'] },
    { term:'for the record', pos:'fixed phrase', meaning:'To state something officially; so there is no misunderstanding.', examples:['<em>For the record</em>, I was not present at that meeting.'] },
    { term:'to that end', pos:'discourse marker', meaning:'In order to achieve that goal.', examples:['We need more qualified staff. <em>To that end</em>, the training budget has been doubled.'] },
    { term:'by no means', pos:'fixed phrase', meaning:'Not at all; absolutely not.', examples:['This is <em>by no means</em> a simple matter.','<em>By no means</em> is this problem unique to our sector.'] },
    { term:'in retrospect', pos:'fixed phrase', meaning:'Looking back with knowledge one has now.', examples:['<em>In retrospect</em>, the early warning signs were clearly visible.'] },
    { term:'inasmuch as', pos:'conj (formal)', meaning:'To the extent that; given that; because.', examples:['The decision was justified, <em>inasmuch as</em> no other option was available.'], note:'Exclusively formal/written register.' },
    { term:'in due course', pos:'fixed phrase', meaning:'At the appropriate time; eventually.', examples:['The committee will publish its findings <em>in due course</em>.'] },
    { term:'with the benefit of hindsight', pos:'fixed phrase', meaning:'Looking back with knowledge gained after the event.', examples:['<em>With the benefit of hindsight</em>, the decision was clearly an error.'] },
    { term:'the fact of the matter is', pos:'fixed phrase', meaning:'Used to introduce the truth, especially when contradicting an assumption.', examples:['<em>The fact of the matter is</em> that no easy solution exists.'] },
    { term:'all things being equal', pos:'fixed phrase', meaning:'If conditions remain the same; other factors aside.', examples:['<em>All things being equal</em>, the project should be completed on time.'] },
    { term:'needless to say', pos:'fixed phrase', meaning:'Introducing something that should be obvious, but bears stating.', examples:['<em>Needless to say</em>, the announcement was met with disbelief.'] },
    { term:'at face value', pos:'fixed phrase', meaning:'As something appears on the surface, without deeper investigation.', examples:['These figures should not be taken <em>at face value</em>.','It is tempting to accept the proposal <em>at face value</em>, but closer inspection reveals problems.'] },
    { term:'without prejudice', pos:'fixed phrase (legal)', meaning:'Without affecting legal rights; without prejudging a case.', examples:['The letter was sent <em>without prejudice</em> and cannot be used as evidence.','Negotiations were conducted <em>without prejudice</em> to either party\'s position.'], note:'Common in legal and commercial correspondence.' },
    { term:'by a wide margin', pos:'fixed phrase', meaning:'By a large amount; decisively.', examples:['She won the vote <em>by a wide margin</em>.','The proposal was defeated <em>by a wide margin</em>.'] },
    { term:'in the same vein', pos:'fixed phrase', meaning:'In the same style or manner; similarly.', examples:['<em>In the same vein</em>, the second report concludes that intervention is necessary.'] },
    { term:'lend credence to', pos:'verb phrase', meaning:'To make something more believable or plausible.', examples:['The new testimony <em>lends considerable credence to</em> the prosecution\'s case.','This evidence <em>lends credence to</em> the conspiracy theory.'] },
    { term:'in the long run', pos:'fixed phrase', meaning:'Over a long period; ultimately.', examples:['<em>In the long run</em>, investment in education yields the greatest returns.'] },
    { term:'at cross purposes', pos:'fixed phrase', meaning:'Misunderstanding each other due to different assumptions or goals.', examples:['The two departments have been working <em>at cross purposes</em> for months.'] },
    { term:'a moot point', pos:'fixed phrase', meaning:'A debatable or irrelevant point; one with no practical significance.', examples:['Whether the original decision was correct is now <em>a moot point</em>.'] },
  ]
},


};
