const THEORY_IDIOMS = {
idioms: {
  title: 'Idioms',
  intro: 'Idioms are fixed expressions whose meaning cannot be derived from individual words. At C1/C2 level they appear in journalism, formal debate, political speech, and professional contexts.',
  entries: [
    { term:'sit on the fence', pos:'idiom', meaning:'To avoid committing to a position.', examples:['You cannot keep <em>sitting on the fence</em> — the vote is tomorrow.'] },
    { term:'open a can of worms', pos:'idiom', meaning:'To create a complicated situation that causes more problems than it solves.', examples:['The investigation <em>opened a can of worms</em> nobody had anticipated.'] },
    { term:'beat around the bush', pos:'idiom', meaning:'To avoid getting to the main point; to speak indirectly.', examples:['Stop <em>beating around the bush</em> and tell me your decision.'] },
    { term:'have the upper hand', pos:'idiom', meaning:'To be in a position of advantage or control.', examples:['After the leak, the opposition finally <em>had the upper hand</em>.'] },
    { term:'weather the storm', pos:'idiom', meaning:'To survive a difficult period.', examples:['The company has <em>weathered storms</em> before and will do so again.'] },
    { term:'burn one\'s bridges', pos:'idiom', meaning:'To permanently destroy a relationship or future opportunity.', examples:['Resigning without notice means she has <em>burned her bridges</em>.'] },
    { term:'bite the bullet', pos:'idiom', meaning:'To endure a painful situation or make a hard unavoidable decision.', examples:['They will have to <em>bite the bullet</em> and announce further cuts.'] },
    { term:'a double-edged sword', pos:'idiom', meaning:'Something with both advantages and disadvantages.', examples:['Transparency is <em>a double-edged sword</em> — it builds trust but exposes vulnerability.'] },
    { term:'skate on thin ice', pos:'idiom', meaning:'To take serious risks; to be in a precarious situation.', examples:['The minister is <em>skating on thin ice</em> with the allegations unresolved.'] },
    { term:'at loggerheads', pos:'idiom', meaning:'In strong, persistent disagreement.', examples:['The two departments have been <em>at loggerheads</em> over the budget for months.'] },
    { term:'pull strings', pos:'idiom', meaning:'To use personal influence to gain an advantage.', examples:['It seemed as though someone was <em>pulling strings</em> behind the scenes.'] },
    { term:'bury the hatchet', pos:'idiom', meaning:'To end a conflict; to make peace.', examples:['After years of rivalry, the two firms finally <em>buried the hatchet</em>.'] },
    { term:'pie in the sky', pos:'idiom', meaning:'An idea that is unrealistically optimistic or impractical.', examples:['The proposal sounds appealing, but it\'s <em>pie in the sky</em> without funding.'] },
    { term:'reinvent the wheel', pos:'idiom', meaning:'To waste effort creating something that already exists.', examples:['There is no need to <em>reinvent the wheel</em> — existing frameworks can be adapted.'] },
    { term:'rock the boat', pos:'idiom', meaning:'To cause unnecessary trouble or disturb a stable situation.', examples:['None of the board members wanted to <em>rock the boat</em> before the results.'] },
    { term:'in the red / in the black', pos:'idiom pair', meaning:'"In the red" = losing money. "In the black" = profitable.', examples:['The firm has been <em>in the red</em> for three consecutive quarters.'] },
    { term:'at the eleventh hour', pos:'idiom', meaning:'At the last possible moment before a deadline.', examples:['A deal was struck <em>at the eleventh hour</em>, averting a strike.'] },
    { term:'pass the buck', pos:'idiom', meaning:'To shift responsibility to someone else.', examples:['He consistently <em>passes the buck</em> rather than taking ownership.'] },
    { term:'go down like a lead balloon', pos:'idiom', meaning:'To be received very badly.', examples:['His attempt at humour <em>went down like a lead balloon</em>.'] },
    { term:'see eye to eye', pos:'idiom', meaning:'To agree completely with someone.', examples:['The two directors don\'t always <em>see eye to eye</em> on strategy.'] },
    { term:'at the helm', pos:'idiom', meaning:'In charge; in a leadership position.', examples:['With a new CEO <em>at the helm</em>, investors are cautiously optimistic.'] },
    { term:'a storm in a teacup', pos:'idiom (BrE)', meaning:'A lot of fuss about something not very important.', examples:['What seemed like a major crisis turned out to be <em>a storm in a teacup</em>.'] },
    { term:'move the goalposts', pos:'idiom', meaning:'To change the rules or criteria unfairly mid-process.', examples:['Every time we met the requirements, they <em>moved the goalposts</em>.'] },
    { term:'the tip of the iceberg', pos:'idiom', meaning:'A small visible part of a much larger problem.', examples:['The few cases that came to light were merely <em>the tip of the iceberg</em>.'] },
    { term:'on borrowed time', pos:'idiom', meaning:'Surviving longer than expected; likely to end soon.', examples:['The coalition government is clearly <em>on borrowed time</em>.'] },
    { term:'a foregone conclusion', pos:'idiom', meaning:'A result certain before it happens; completely predictable.', examples:['The re-election was widely seen as <em>a foregone conclusion</em>.'] },
    { term:'in the same breath', pos:'idiom', meaning:'At the same time; often highlighting a contradiction.', examples:['He praised the employees and, <em>in the same breath</em>, announced the layoffs.'] },
    { term:'draw a line under', pos:'idiom', meaning:'To decide something is finished and should not be revisited.', examples:['The settlement was intended to <em>draw a line under</em> years of litigation.'] },
    { term:'take with a pinch of salt', pos:'idiom', meaning:'To be sceptical about something; not to take it literally.', examples:['His optimistic forecasts should be <em>taken with a pinch of salt</em>.'] },
    { term:'blow the whistle on', pos:'idiom', meaning:'To expose wrongdoing by reporting it.', examples:['She <em>blew the whistle on</em> the accounting irregularities.'] },
    { term:'keep a low profile', pos:'idiom', meaning:'To avoid attracting attention or publicity.', examples:['Following the scandal, the minister chose to <em>keep a low profile</em>.'] },
    { term:'give someone the benefit of the doubt', pos:'idiom', meaning:'To accept someone\'s explanation as true without proof.', examples:['In the absence of evidence to the contrary, we should <em>give him the benefit of the doubt</em>.'] },
    { term:'a level playing field', pos:'idiom', meaning:'A situation in which all parties compete under the same conditions.', examples:['The reforms were designed to create <em>a level playing field</em>.'] },
    { term:'gain ground', pos:'idiom', meaning:'To make progress; to become more accepted.', examples:['The opposition is gradually <em>gaining ground</em> in the polls.'] },
    { term:'ring-fence', pos:'idiom / verb', meaning:'To protect an area from cuts or interference.', examples:['The education budget has been <em>ring-fenced</em> despite wider cuts.'] },
    { term:'go back to the drawing board', pos:'idiom', meaning:'To start planning again from the beginning after a failure.', examples:['After the rejection, the team had to <em>go back to the drawing board</em>.'] },
    { term:'throw down the gauntlet', pos:'idiom', meaning:'To make a challenge or demand; to provoke someone.', examples:['The new legislation <em>threw down the gauntlet</em> to the entire industry.'] },
    { term:'leave no stone unturned', pos:'idiom', meaning:'To try every possible means to achieve something.', examples:['The investigators promised to <em>leave no stone unturned</em> in their search.'] },
    { term:'cut to the chase', pos:'idiom', meaning:'To get to the important point immediately, without preamble.', examples:['Let me <em>cut to the chase</em>: the project is over budget.'] },
    { term:'in the pipeline', pos:'idiom', meaning:'Being planned or in preparation; forthcoming.', examples:['Several new initiatives are <em>in the pipeline</em>.','Further legislation is reportedly <em>in the pipeline</em>.'] },
    { term:'set a precedent', pos:'idiom', meaning:'To establish a standard for future cases.', examples:['The ruling <em>sets a dangerous precedent</em> for future cases.'] },
    { term:'in the doldrums', pos:'idiom', meaning:'In a period of little activity, growth, or progress.', examples:['The economy has been <em>in the doldrums</em> for several quarters.'] },
    { term:'fly in the face of', pos:'idiom', meaning:'To be completely contrary to; to openly go against.', examples:['This policy <em>flies in the face of</em> all available evidence.'] },
    { term:'bear fruit', pos:'idiom', meaning:'To produce results or yield benefits.', examples:['Years of investment are finally beginning to <em>bear fruit</em>.','The research programme has not yet <em>borne fruit</em>.'] },
    { term:'pave the way for', pos:'idiom', meaning:'To create conditions that make something possible.', examples:['The agreement <em>paves the way for</em> full diplomatic relations.'] },
    { term:'a watershed moment', pos:'idiom', meaning:'A turning point after which things will never be the same.', examples:['The trial was <em>a watershed moment</em> in the history of civil rights.'] },
    { term:'keep tabs on', pos:'idiom', meaning:'To monitor someone or something carefully.', examples:['The regulator is <em>keeping close tabs on</em> the company\'s compliance.'] },
    { term:'put something on the back burner', pos:'idiom', meaning:'To delay dealing with something, giving it lower priority.', examples:['The proposal was <em>put on the back burner</em> due to funding constraints.'] },
    { term:'on the cusp of', pos:'idiom', meaning:'At the point where something is about to happen.', examples:['The technology is <em>on the cusp of</em> widespread commercial deployment.'] },
    { term:'a baptism of fire', pos:'idiom', meaning:'A difficult introduction to a new role or experience.', examples:['Her first week as CEO was a real <em>baptism of fire</em>.'] },
    { term:'hedge one\'s bets', pos:'idiom', meaning:'To protect oneself against risk by supporting more than one option.', examples:['By investing in multiple markets, the fund was <em>hedging its bets</em>.'] },
    { term:'paper over the cracks', pos:'idiom', meaning:'To conceal problems superficially without solving them.', examples:['The agreement merely <em>papers over the cracks</em> in the coalition.'] },
    { term:'tilt the balance', pos:'idiom', meaning:'To shift something towards a particular outcome.', examples:['This new evidence could <em>tilt the balance</em> in favour of the defence.'] },
    { term:'come to a standstill', pos:'idiom', meaning:'To stop completely.', examples:['Production <em>came to a complete standstill</em> during the strike.'] },
    { term:'take the bull by the horns', pos:'idiom', meaning:'To deal with a difficult situation in a direct and determined way.', examples:['It was time to <em>take the bull by the horns</em> and confront the board.'] },
    { term:'on the back foot', pos:'idiom', meaning:'In a defensive or disadvantaged position.', examples:['The minister was immediately <em>put on the back foot</em> by the revelation.'] },
    { term:'push the envelope', pos:'idiom', meaning:'To go beyond accepted limits; to do something more extreme than before.', examples:['The research team is constantly <em>pushing the envelope</em> of what is technologically feasible.'] },
    { term:'a blessing in disguise', pos:'idiom', meaning:'Something that appears bad but turns out to be beneficial.', examples:['Losing that contract turned out to be <em>a blessing in disguise</em>.'] },
    { term:'hit the nail on the head', pos:'idiom', meaning:'To describe or identify something exactly correctly.', examples:['Her analysis really <em>hit the nail on the head</em>.'] },
    { term:'in full swing', pos:'idiom', meaning:'At the most active stage; in full operation.', examples:['The election campaign is now <em>in full swing</em>.','Reconstruction is <em>in full swing</em>.'] },
    { term:'steal a march on', pos:'idiom', meaning:'To gain an advantage over someone by acting before they do.', examples:['The company has <em>stolen a march on</em> its rivals by filing the patent first.'] },
    { term:'bring to heel', pos:'idiom', meaning:'To force to obey or submit to authority.', examples:['The regulator moved swiftly to <em>bring the company to heel</em>.'] },
  ]
},


};
