const THEORY_INVERSION = {
inversion: {
  title: 'Inversion',
  intro: 'Inversion — placing the auxiliary before the subject — is a key C1/C2 structure used for emphasis and formal register. It is triggered by specific negative, restrictive, or conditional expressions and is directly tested in CAE and CPE.',
  entries: [
    { term:'Not only...but also', pos:'inversion structure', meaning:'Used for emphasis. Inversion required in the first clause; normal order after "but".', examples:['<em>Not only did</em> she misrepresent the facts, but she also destroyed the evidence.','<em>Not only has</em> the company failed to meet targets, but it has also lost key clients.'], note:'The auxiliary (did/has/was/is) goes before the subject. The infinitive is bare.' },
    { term:'Hardly / Scarcely...when/before', pos:'inversion structure', meaning:'"Almost no time had passed when..." Inversion required.', examples:['<em>Hardly had</em> he sat down when the phone rang.','<em>Scarcely had</em> the announcement been made before protests erupted.'], note:'Use past perfect in the inverted clause. "When/before" — NOT "than".' },
    { term:'No sooner...than', pos:'inversion structure', meaning:'"Immediately after..." Inversion required.', examples:['<em>No sooner had</em> she left the room than an argument broke out.'], note:'ALWAYS "than" — never "when" with "no sooner".' },
    { term:'Under no circumstances', pos:'inversion structure', meaning:'For absolute prohibition or denial.', examples:['<em>Under no circumstances should</em> this information be disclosed.','<em>Under no circumstances are</em> visitors permitted beyond this point.'] },
    { term:'Never / Rarely / Seldom', pos:'inversion structure', meaning:'Negative adverb at the start of a sentence triggers inversion.', examples:['<em>Never before had</em> the country faced such a severe crisis.','<em>Rarely does</em> a study produce such unambiguous results.','<em>Seldom have</em> we witnessed such effective leadership.'] },
    { term:'Only after / Only when / Only by', pos:'inversion structure', meaning:'"Only + adverbial phrase" at the start triggers inversion in the main clause.', examples:['<em>Only after</em> the vote <em>did</em> the full implications become clear.','<em>Only by</em> restructuring the debt <em>can</em> the company survive.','<em>Only when</em> all evidence has been presented <em>can</em> a verdict be reached.'] },
    { term:'Such...that / So...that', pos:'inversion (formal emphasis)', meaning:'Used for dramatic effect to emphasise degree or extent.', examples:['<em>Such was</em> the scale of the disaster that international aid was mobilised.','<em>So acute was</em> the shortage that rationing was immediately introduced.'] },
    { term:'Were it not for / Had it not been for', pos:'conditional inversion', meaning:'Formal alternatives to "If it were not for / If it had not been for". No "if".', examples:['<em>Were it not for</em> the court\'s intervention, the merger would have proceeded.','<em>Had it not been for</em> his quick thinking, the consequences could have been catastrophic.'], note:'Third conditional: "Had she known, she would have acted differently." (= If she had known).' },
    { term:'On no account', pos:'inversion structure', meaning:'Under no circumstances; strong prohibition.', examples:['<em>On no account should</em> the media be given access to those files.'] },
    { term:'Little did...know', pos:'inversion structure', meaning:'"Little" in the negative sense at the start.', examples:['<em>Little did</em> anyone <em>know</em> that the company was already insolvent.','<em>Little did</em> she <em>realise</em> how significant that meeting would prove.'] },
    { term:'At no point / At no time', pos:'inversion structure', meaning:'Used to emphasise that something never happened.', examples:['<em>At no point</em> during the investigation <em>was</em> evidence of fraud found.','<em>At no time did</em> the accused act alone.'] },
    { term:'Not until / Not since', pos:'inversion structure', meaning:'"Not until/since [time]" at the start triggers inversion in the main clause.', examples:['<em>Not until</em> the report was published <em>did</em> the public grasp the full extent.','<em>Not since</em> the war <em>had</em> the country faced such hardship.'] },
    { term:'In no way / In no sense', pos:'inversion structure', meaning:'Used to strongly deny or negate something.', examples:['<em>In no way does</em> this decision reflect the views of the committee.','<em>In no sense can</em> this be considered a satisfactory outcome.'] },
    { term:'Nor / Neither...', pos:'inversion structure', meaning:'"Nor/Neither" at the start of a clause = inversion.', examples:['The first report was inconclusive. <em>Nor did</em> the second provide any clarity.','She could not accept the terms. <em>Neither could</em> her legal team.'] },
    { term:'Should (formal conditional)', pos:'conditional inversion', meaning:'Formal alternative to "If it should happen that..."', examples:['<em>Should</em> you require further information, please do not hesitate to contact us.','<em>Should</em> the situation change, the committee will reconvene immediately.'], note:'Commonly used in formal correspondence and legal language.' },
    { term:'Were (present/future hypothetical)', pos:'conditional inversion', meaning:'Formal alternative to "If it were..." (subjunctive).', examples:['<em>Were</em> the evidence more conclusive, a different verdict might have been reached.','<em>Were</em> the company to collapse, thousands of jobs would be at risk.'] },
    { term:'Had (past hypothetical)', pos:'conditional inversion', meaning:'Formal alternative to "If...had..." in the third conditional.', examples:['<em>Had</em> the government acted sooner, the crisis might have been averted.','<em>Had</em> we been informed, we would have responded immediately.'] },
  ]
},


};
