const THEORY_DISCOURSE = {
discourse: {
  title: 'Discourse Markers',
  intro: 'Discourse markers organise written and spoken text, signalling logical relationships. Mastery of these distinguishes C1 from C2 and is essential for academic writing and formal speech.',
  entries: [
    { term:'Addition', pos:'category', meaning:'Adding information, evidence, or arguments in the same direction.', examples:['<em>Furthermore</em>, the evidence suggests a deeper systemic failure.','<em>Moreover</em>, the committee had been warned months in advance.','<em>In addition to</em> this, three witnesses have since retracted their statements.','<em>What is more</em>, the company knew about the risks and did nothing.','<em>Added to this</em>, the regulatory framework is clearly inadequate.','<em>By the same token</em>, the costs of inaction must also be considered.'] },
    { term:'Contrast & Concession', pos:'category', meaning:'Introducing an opposing or qualifying point.', examples:['<em>Nevertheless</em>, the project continued despite widespread objections.','<em>Notwithstanding</em> these concerns, a decision was reached.','<em>Be that as it may</em>, the results are clear.','<em>That said</em>, there are legitimate reasons for caution.','<em>Even so</em>, the proposal merits serious consideration.','<em>For all that</em>, the outcome was better than feared.','<em>While it is true that</em>...','<em>Admittedly</em>, not all the evidence points in the same direction.'] },
    { term:'Cause and Result', pos:'category', meaning:'Showing logical consequence or causal relationship.', examples:['<em>Consequently</em>, the firm was placed in administration.','<em>As a result of</em> the delays, the contract was terminated.','<em>This in turn led to</em> a broader crisis of confidence.','<em>It follows that</em> further investment is necessary.','<em>Hence</em>, the need for a thorough and independent audit.','<em>By extension</em>, the same logic applies to the wider sector.'] },
    { term:'Condition', pos:'category', meaning:'Introducing conditions, formal or tentative.', examples:['<em>Provided that</em> the terms are met, the agreement will stand.','<em>Subject to</em> approval, work can begin next month.','<em>On the condition that</em> no further objections are raised, the motion will pass.','<em>Assuming (that)</em> the data are accurate, the model is robust.','<em>In the event that</em> a settlement cannot be reached, the case will go to trial.','<em>Failing that</em>, the matter will be referred to arbitration.'] },
    { term:'Reformulation & Clarification', pos:'category', meaning:'Restating or clarifying for greater precision.', examples:['<em>In other words</em>, the policy has failed on every measurable outcome.','<em>To put it another way</em>, the risk is unacceptable.','<em>That is to say</em>, full compliance is mandatory.','<em>More specifically</em>, the problem lies in the wording of the third clause.','<em>To be more precise</em>, the shortfall amounts to £4.2 million.','<em>To clarify</em>, the proposal does not affect existing contracts.'] },
    { term:'Summary & Conclusion', pos:'category', meaning:'Drawing together points or reaching a conclusion.', examples:['<em>In conclusion</em>, the evidence overwhelmingly supports immediate reform.','<em>To sum up</em>, three key structural failures have been identified.','<em>All things considered</em>, the proposal represents a reasonable compromise.','<em>In the final analysis</em>, accountability must rest with the leadership.','<em>On balance</em>, the benefits appear to outweigh the risks.','<em>Taking everything into account</em>, a cautious approach is advisable.','<em>To draw matters to a close</em>, the key recommendations are as follows.'] },
    { term:'Exemplification', pos:'category', meaning:'Introducing examples or specific instances.', examples:['<em>For instance</em>, the carbon tax in Sweden has reduced emissions by 26%.','<em>To illustrate</em>, consider the case of the 2008 financial crisis.','<em>Take, for example</em>, the disparity in educational outcomes.','<em>This is evidenced by</em> the sharp rise in insolvencies.','<em>A case in point is</em> the collapse of Lehman Brothers.','<em>To give a concrete example</em>...'] },
    { term:'Emphasis', pos:'category', meaning:'Highlighting the most important or surprising point.', examples:['<em>Above all</em>, transparency is non-negotiable.','<em>What is particularly striking is</em> the speed of the deterioration.','<em>It is worth noting that</em> no formal complaint was ever filed.','<em>Crucially</em>, the evidence was never independently verified.','<em>Of particular significance is</em> the absence of regulatory oversight.','<em>It cannot be overstated that</em> this represents a fundamental failure.'] },
    { term:'Hedging & Tentativeness', pos:'category', meaning:'Softening or qualifying claims for academic, diplomatic, or cautious purposes.', examples:['<em>It would appear that</em> the system was compromised from within.','<em>There is reason to believe that</em> the data were selectively presented.','<em>It could be argued that</em> the initial response was inadequate.','<em>To some extent</em>, this reflects a wider structural problem.','<em>One might suggest that</em> a more measured approach was called for.','<em>It seems likely that</em> the full impact will only become clear over time.','<em>The evidence suggests, albeit tentatively, that</em>...'] },
    { term:'Sequence & Order', pos:'category', meaning:'Organising information in logical or chronological order.', examples:['<em>In the first instance</em>, an independent audit must be commissioned.','<em>Subsequently</em>, the committee will review the findings.','<em>Prior to</em> any decision, all stakeholders must be consulted.','<em>In the interim</em>, operations will continue as normal.','<em>Following this</em>, a formal report will be submitted to Parliament.','<em>Thereafter</em>, the matter will be referred to the oversight board.'] },
    { term:'Digression & Return', pos:'category', meaning:'Moving temporarily away from the main point and signalling a return.', examples:['<em>As an aside</em>, it is worth mentioning that the original proposal was never formally withdrawn.','<em>Incidentally</em>, the same error appears in the 2019 report.','<em>To return to the main point</em>, the core issue remains unresolved.','<em>To come back to</em> the question of funding — no clear answer has been provided.'] },
    { term:'Concessive clauses', pos:'category', meaning:'Acknowledging an opposing point while maintaining the main argument.', examples:['<em>While it must be acknowledged that</em> progress has been made, significant challenges remain.','<em>Although one could argue that</em> the measure was justified, the execution was poor.','<em>Granted that</em> the evidence is limited, the conclusion is nonetheless compelling.','<em>Much as</em> the government would like to avoid further cuts, the fiscal position leaves little choice.'] },
  ]
},


};
